### ISSUE TITLE
Client Allocation Request for: wang liang

### ISSUE THREAD

**Issue by imageorbit** [keyko-io/filecoin-clients-onboarding#100]
---

# Client Allocation Questions 

## Core Information
- Name: wang liang
- Website / Social Media: imageorbit.space
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q
- Notary Requested: philippbanhardt

**Comment by imageorbit** [comment]
The previous 1T DataCap is used. 
Check message is sent in fil-plus slack.
Previous application: https://github.com/keyko-io/filecoin-clients-onboarding/issues/29

We will store more copies of imagenet and google open image dataset. They are all public data set.

ImageNet: an image database organized according to the WordNet hierarchy, 1.2T, jpeg http://www.image-net.org/
Open Images Dataset:9 million URLs to images that have been annotated with labels spanning over 6000 categories  , 18T, jpeg/PNG, https://storage.googleapis.com/openimages/web/index.html

**Comment by philippbanhardt** [comment]
Hey @imageorbit , can you kindly share the deal transactions here from the previous 1TB used?

**Comment by imageorbit** [comment]
client | deal_id | deal_start_epoch | miner_id | payload_cid | data_size
-- | -- | -- | -- | -- | --
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1390660 | 277358 | f060072 | bafykbzacediyv3ermoyhtx3tbb2ltoqidhe6oj4ifoabgvbqoqetw67u6ebaa | 34359738368
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1380080 | 270883 | f053088 | bafykbzacecfuir2tvcrkhlmwwxx5nmota4bp7acsj3g6jamuxqnoi3igazajg | 34359738368
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1383648 | 272782 | f021961 | bafykbzacebamrvttfmvlsmmzt5fzbkyx662dauq3h2t5jpnkjpuafqyjyo7bu | 34359738368
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1382542 | 270023 | f060072 | bafykbzaceda4y5o5s77adwmmd6kk36r33iod5i24ykj32mivab64heeuuzlx2 | 34359738368
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1392156 | 278093 | f010505 | bafykbzacedgp6ef5euruvhnnabrunsthocgjptdqukn7qx3s2puhtxw6g6tni | 34359738368
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1387270 | 277211 | f060072 | bafykbzacedherk2xxg6ykvyc5q5vlei45movgtji7hd2wehvvwpkoa7vdbt5o | 34359738368
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1379503 | 270239 | f053088 | bafykbzacedxfcnhk37htsdfeq7cnfcg3aiumhik3mgg3idq6alx4kum5o6erw | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1416054 | 295499 | f08240 | bafykbzacecms3iigkq34e2hzjsrsi6mq7xqbiltfjrqoadjrmcie2q7cjzfzw | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1387276 | 277341 | f060072 | bafykbzacedx5gusote7ifrmtetpm5nlh3ilmihllnqjzas7oqmvpphgtswkdi | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1390875 | 277346 | f060072 | bafykbzacedu2xjgi6wde3vbvrzb27jk3jzbhrvhevcujo3lqidzx6bq45g5xg | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1380229 | 270757 | f053088 | bafykbzacedvzwlfoourrplk7m3xd6dm4cmhkk6zkbaayvu2kajzbp2u2p45o4 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1381204 | 270757 | f053088 | bafykbzacec2klpbnrndbltworzfkzhpbjsbb7pepnogo2gsq47kafufpavn2y | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1383454 | 272877 | f021961 | bafykbzacebfjfaotglxnkkqjinm6uk45vgziytficta7xvdscs24t6yzm33hy | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1386204 | 273100 | f021961 | bafykbzaced42xgeoholex5jkhfcfjq5j2skmq7tyemahi64jt5lwmyz7akkts | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1387275 | 277235 | f060072 | bafykbzacecykifpwoa2aa2re7csa6ze3zi7on7hrq76bbx4wrtuv2k7dip4ck | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1392149 | 281365 | f053088 | bafykbzacedzlmeqxpnhhre46mfi5fmapr32veruwvd5i5am4gpvjpidkinsv2 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1416461 | 295116 | f019551 | bafykbzaceanrghuv25hsggufr3marzzlgnugltbuj3khj3qvp45ut3svjllxo | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1415831 | 294474 | f023467 | bafykbzaceclzq73xnnjgrfyzrbcf55apkovbmh57ykdbbapku6g3slrpif5ny | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1415757 | 294366 | f023467 | bafykbzaceanrghuv25hsggufr3marzzlgnugltbuj3khj3qvp45ut3svjllxo | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1378215 | 270239 | f053088 | bafykbzacecmgsjyehk6rkbq7deoowhpe46dbimj6yz3uwvf3jfwq6q6vb7tti | 8589934592
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1387274 | 277341 | f060072 | bafykbzaceb6fhn2cmfph6o5jb4qqqhh7uyoaqertrt52f4urpbqtzevf526du | 8589934592
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1387272 | 277235 | f060072 | bafykbzaced4hxnvtqz7osplahqivhy5xauegq73c4gneuqcflghmg24g7iyaw | 8589934592
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1379115 | 270297 | f010491 | bafykbzaceaswkrwehdmoaagk3355is7fuien26qmf2kun5nmllyqf2e2ghho2 | 8589934592
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1384259 | 273482 | f021961 | bafykbzacec3jw5v3rd77pj4ph2bmyry24byqssfcdve6xhjpssiruviqjpdui | 8589934592
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1390971 | 277375 | f060072 | bafykbzacebznoe7ert75as2cn4wqnseynfjmwsnljczz73emr4nofuq4ew2cq | 4294967296
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1387277 | 277341 | f060072 | bafykbzaceadliymdzw2s6kptce62brikmokwsh7ctwjeshwdp2dmlddg7dtl4 | 4294967296
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1391364 | 278145 | f060072 | bafyaa6qsgafcmalqudsaeia2usustyigdxd3gcs5fkbxc33ayihsim5bpd6bmcyld7h7ehoamejaagelucbyabasgafcmalqudsaeifv2e2zcsl6efjzcldgvfaqpzpfay3qnr2647bkupxwi5solsro6qjaageiu3tlgaikcqeaegg5sps3gbjaqcaibaaeedozhzn | 2147483648
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1391315 | 278133 | f060072 | bafyaa6qsgafcmalqudsaeibeqvi7bkrs7qpfspj5w6xyie2n4zvk3y57zjnpmeeyvayocdc3wujaagelucbyabasgafcmalqudsaeih4sl6vhrzeinhlpdfk63exesgcoykkxdevlb2eqtmsqcpdxyhypyjaaggiukp46aikcqeaeghr7go46bjaqcaibaaeedy7tho | 2147483648
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1391316 | 278144 | f060072 | bafyaa6qsgafcmalqudsaeig4iqh3pxryucb7cqxrpb25mjgjl34yu6uxqt2m7oqsxz7wxkncamjaagelucbyabasgafcmalqudsaeigr7tg4ci6qetouxhqyggjxrhi5ydfmqxbvnqc5dsnrerzxaaeujyjaagh53ghi4aqkcqeaegeo72gi4braqcaibaaeechp5de | 2147483648
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1411030 | 290596 | f08240 | bafykbzacebnerc7qxanmbzazawangs45574lvyhu7ts5m4ollibhob55nt7va | 268435456
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1381330 | 271840 | f053088 | bafykbzacebpup3fgvozcvfq7pjhwezgeypaiw4kin4v56i3zdxl3jwcxw6de6 | 268435456
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1406493 | 284758 | f01276 | bafykbzaceakmmvj7ahpud4bhscbmi2ccioznhrry2jxazhsptqojk2lz742nk | 16777216
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1394675 | 282380 | f08240 | bafykbzaceakmmvj7ahpud4bhscbmi2ccioznhrry2jxazhsptqojk2lz742nk | 16777216
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1394662 | 282380 | f08240 | bafykbzaceakmmvj7ahpud4bhscbmi2ccioznhrry2jxazhsptqojk2lz742nk | 16777216
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420093 | 296317 | f040332 | bafykbzacea46sy4pdupce4d6will2c5zko3suh2zuohmttg4ne4jgav2djpxi | 34359738368
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420269 | 296805 | f023467 | bafykbzacedxkiqt54uvpqftnjkaf224iuh3lmdars6mgdumbglwyjgfmardx2 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420065 | 296698 | f023467 | bafykbzaceacte5ogixwrcnix3yhawamfqgw6pwekigv4xezl2llwu5wie4ufg | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419651 | 296465 | f022352 | bafykbzacecms3iigkq34e2hzjsrsi6mq7xqbiltfjrqoadjrmcie2q7cjzfzw | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419744 | 296444 | f022352 | bafykbzacedxkiqt54uvpqftnjkaf224iuh3lmdars6mgdumbglwyjgfmardx2 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419295 | 296047 | f023467 | bafykbzaceanrghuv25hsggufr3marzzlgnugltbuj3khj3qvp45ut3svjllxo | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419718 | 296474 | f022352 | bafykbzaceagjbxhyswfc6ljyouphxsgdtpnfwkw35tzvzp7vn4nimwdxesgmq | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1416061 | 295903 | f08240 | bafykbzaceagjbxhyswfc6ljyouphxsgdtpnfwkw35tzvzp7vn4nimwdxesgmq | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419719 | 296387 | f022352 | bafykbzaceclzq73xnnjgrfyzrbcf55apkovbmh57ykdbbapku6g3slrpif5ny | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419996 | 296482 | f023467 | bafykbzaceagjbxhyswfc6ljyouphxsgdtpnfwkw35tzvzp7vn4nimwdxesgmq | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419850 | 296372 | f023467 | bafykbzaceaw4ykwbr7mzuc7gb6smdczekdklftujmah556vsyxvctinuhpk6w | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420994 | 296645 | f019551 | bafykbzaceb2jamxrkfpkohrfhcjdlge76zl6yxwlbvsphujrr3jzgfqumgubw | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419288 | 295990 | f023467 | bafykbzacecgv6r7ypkrep7yuewnizekchc2d5ovulbhb5phgbhxeicbb4ek72 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419714 | 296157 | f023467 | bafykbzacecgv6r7ypkrep7yuewnizekchc2d5ovulbhb5phgbhxeicbb4ek72 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1418467 | 296832 | f09848 | bafykbzaceagjbxhyswfc6ljyouphxsgdtpnfwkw35tzvzp7vn4nimwdxesgmq | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1415698 | 296469 | f022142 | bafykbzaceagjbxhyswfc6ljyouphxsgdtpnfwkw35tzvzp7vn4nimwdxesgmq | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419983 | 296485 | f022352 | bafykbzacedxkiqt54uvpqftnjkaf224iuh3lmdars6mgdumbglwyjgfmardx2 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420266 | 296529 | f019551 | bafykbzaceagjbxhyswfc6ljyouphxsgdtpnfwkw35tzvzp7vn4nimwdxesgmq | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420174 | 296591 | f023467 | bafykbzacedxkiqt54uvpqftnjkaf224iuh3lmdars6mgdumbglwyjgfmardx2 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420229 | 296805 | f023467 | bafykbzacea5skr3oohihjzy3bvb6ogamhd6l5wiptfrmnppgetnuto4vcdzzo | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420173 | 296591 | f023467 | bafykbzaceacte5ogixwrcnix3yhawamfqgw6pwekigv4xezl2llwu5wie4ufg | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420050 | 296482 | f023467 | bafykbzaceanrghuv25hsggufr3marzzlgnugltbuj3khj3qvp45ut3svjllxo | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1417789 | 295908 | f019551 | bafykbzaceagjbxhyswfc6ljyouphxsgdtpnfwkw35tzvzp7vn4nimwdxesgmq | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419710 | 296047 | f023467 | bafykbzaceaw4ykwbr7mzuc7gb6smdczekdklftujmah556vsyxvctinuhpk6w | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419711 | 296157 | f023467 | bafykbzacedxkiqt54uvpqftnjkaf224iuh3lmdars6mgdumbglwyjgfmardx2 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420096 | 296698 | f023467 | bafykbzacedxkiqt54uvpqftnjkaf224iuh3lmdars6mgdumbglwyjgfmardx2 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419285 | 295990 | f023467 | bafykbzacecms3iigkq34e2hzjsrsi6mq7xqbiltfjrqoadjrmcie2q7cjzfzw | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419860 | 296372 | f023467 | bafykbzaceclzq73xnnjgrfyzrbcf55apkovbmh57ykdbbapku6g3slrpif5ny | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420995 | 296645 | f019551 | bafykbzaceacte5ogixwrcnix3yhawamfqgw6pwekigv4xezl2llwu5wie4ufg | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419739 | 296263 | f023467 | bafykbzacedxkiqt54uvpqftnjkaf224iuh3lmdars6mgdumbglwyjgfmardx2 | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1419836 | 296263 | f023467 | bafykbzaceacte5ogixwrcnix3yhawamfqgw6pwekigv4xezl2llwu5wie4ufg | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1418037 | 297483 | f01278 | bafykbzacea5skr3oohihjzy3bvb6ogamhd6l5wiptfrmnppgetnuto4vcdzzo | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1418036 | 298150 | f01278 | bafykbzaceb2jamxrkfpkohrfhcjdlge76zl6yxwlbvsphujrr3jzgfqumgubw | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1420993 | 298282 | f019551 | bafykbzacea5skr3oohihjzy3bvb6ogamhd6l5wiptfrmnppgetnuto4vcdzzo | 17179869184
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q | 1417961 | 298150 | f01278 | bafykbzaceanrghuv25hsggufr3marzzlgnugltbuj3khj3qvp45ut3svjllxo | 17179869184

**Comment by imageorbit** [comment]
All file are zip file. Part data is from imagenet data set.The other is google open image date set.
I want to store only imagenet data set as applied in https://github.com/keyko-io/filecoin-clients-onboarding/issues/29 at first.
But for a little bug, some data  google open image date set is also stored.
This bug(https://github.com/filecoin-project/lotus/issues/5073) is submitted and revised.

**Comment by philippbanhardt** [comment]
Hey @imageorbit unfortunately given the current Filecoin implementation I can not award additional data cap to an address that already has been granted data cap. A proposal to change this already exists, but will take more time. So in the meantime I propose to grant the additional data cap to a new address if that works for you?

**Comment by imageorbit** [comment]
yes , of course:)
here is my new address:
f3sar6tat2mhqadlqjjxewmpqya3whpkzuqaevpo5vwfvdhnm3uztd7p67d6ozpsfkiwvrvqrhp3zu6psi23ma

**Comment by philippbanhardt** [comment]
Hey @imageorbit  I've granted 4 TiB to the above address - which adding the 1TiB you had received previously adds up to 5 TiB total, the maximum we are prepared to award to an individual client (at least throughout the beta).

Verify Client Message sent with ID: bafy2bzaceamrj6d6adn2p2ox63hipvuarrbmuxk74vbcgucaykzu6s6mxxvyo
