### ISSUE TITLE
Client Allocation Request for: Mar.Pool

### ISSUE THREAD

**Issue by echoboss** [keyko-io/filecoin-clients-onboarding#101]
---

# Client Allocation Questions 

## Core Information
- Name: Mar.Pool
- Website / Social Media: blog.sreinfo.com
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1vxswenfqy2cj7wvuvy5gnr3tw7df3ffeemheucy
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @echoboss - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
