### ISSUE TITLE
Client Allocation Request for: Shanghai Futures Exchange

### ISSUE THREAD

**Issue by hopsum** [keyko-io/filecoin-clients-onboarding#102]
---

# Client Allocation Questions 

## Core Information
- Name: Shanghai Futures Exchange
- Website / Social Media: www.shfe.com.cn
- DataCap Requested: 4TiB
- Addresses to be Notarized: f1jp2xt7qkgdfmsj6pylcalmr7t4atfby2aoyeh4i
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @hopsum - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by hopsum** [comment]
Hi ,thanks philipp!

**About SHFE and myself**
•	Ran Tao  https://www.linkedin.com/in/%E7%84%B6-%E9%99%B6-27b132b0/?originalSubdomain=cn
I graduated from Shandong University in China with a PHD in financial mathematics six years ago. At present, I'm engaged in option pricing in Shanghai Futures Exchange and research on risk control algorithm of financial derivatives. For a long time, I have been paying attention to the safe storage of algorithmic data.
•	Shanghai Futures Exchange：    http://www.shfe.com.cn/en/
With the ultimate goal of serving the real economy,  Shanghai Futures Exchange (“SHFE”) is under the uniform regulation of China Securities Regulatory Commission (“CSRC”) and organizes the futures trading approved by CSRC in accordance with the principles of openness, impartiality, fairness and integrity. Currently there are 20 futures contracts and 5 commodity options available for trading on SHFE, including the futures on copper, aluminum, zinc, lead, nickel, tin, gold, silver, steel rebar, steel wire rod, hot rolled coil, fuel oil, crude oil, bitumen, natural rubber, woodpulp, TSR 20, stainless steel, LSFO and bonded copper, and also copper option, natural rubber option , gold option, aluminum option and zinc option.

**History working on IPFS/Filecoin**
The Shanghai Futures Exchange was established in November 1990. It has a history of 30 years. We produce more than 30T data every day, which is also the basis of our algorithm research. For a long time, we have stored data by building our own private cloud of storage. In recent years, blockchain tech continue to have a significant impact on the financial system, so we also set up a dedicated project team to study it. IPFS/Filecoin, as well as many other distributed storage innovation projects are the new technologies will eventually booming up our businesses like ours. In October this year, I attended the 6th Global Blockchain Summit held in Shanghai, I carefully studied the speech of Juan Benet, the founder of IPFS/Filecoin. He expressed the hope that more valuable data can enter the filecoin system, and we are also very interested in this and willing to make some attempts.

**Type and source of the data looking to store on Filecoin**
To be honest, we have a huge amount of transaction data to store, but a lot of financial data that has not been desensitized is not suitable for testing. So we will consider a small part of the desensitized public trading data and archive data to experience the filecoin system, focusing on testing the service performance of storage and transmission stability.

 As some affiliated institutions of the Shanghai Futures Exchange, data from the following site maybe included. E.g:
http://www.shfe.com.cn/about/branch/sw/
http://www.sfit.com.cn/
http://www.shfe.com.cn/about/branch/yjy/
http://www.ine.cn/

**How you intend to store the data on Filecoin**
Our customers are all over the world, but the local customers will be more concentrated. More than 76% of the visits come from China, and about 15% from NA and EU. We prefer to use multiple miners to work together to complete the test experience. This is a interesting thing, and it is also a very forward-looking exploration. We have the will to participate .

**Comment by philippbanhardt** [comment]
Hey @hopsum thanks for providing the additional information. Are you OK to post here transaction links to the storage deals, once awarded data cap? Also on a related note - wanted to highlight that we are keen to foster decentralization of the network, so would encourage clients to store (redundantly) across a number of miners, as well as not engage in excessive / unfair self-dealing (in case you are running your own mining operation also).

**Comment by hopsum** [comment]
Of course, no problem! We are willing to store our data through decentralized miners and post the transaction links here when we finish the operation.  Thanks again!

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedar23uyhtczdl3p4rny5in5owiphniyodlrx7axs6uz5oi6o35eu 
#### Address 
> f1jp2xt7qkgdfmsj6pylcalmr7t4atfby2aoyeh4i
#### Datacap Allocated
> 4 TiB

**Comment by Eliovp** [comment]
> Of course, no problem! We are willing to store our data through decentralized miners and post the transaction links here when we finish the operation. Thanks again!

Hahaha

Addresses to be Notarized: f1jp2xt7qkgdfmsj6pylcalmr7t4atfby2aoyeh4i

![VeryDecentralized](https://user-images.githubusercontent.com/20194745/111220195-292acb80-85d9-11eb-9441-fc1c6f1c9d35.PNG)

Keep it up! 🤦‍♂️
