### ISSUE TITLE
Client Allocation Request for: IPFS-Scholar

### ISSUE THREAD

**Issue by liyue634** [keyko-io/filecoin-clients-onboarding#110]
# Client Allocation Questions 

## Core Information
- Name: IPFS-scholar
- Website / Social Media: ipfs.zenpool.io
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1vaxz47wmq5ne6ph7rc4yi66lmrlhxeijebogvuy
- Notary Requested: philippbanhardt

-----------------------------

**Comment by philippbanhardt** [comment]
Hey @liyue634 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by liyue634** [comment]
- Name：Cao Ling
- Social media and websites：[GitHub](https://github.com/liyue634 ) [IPFS-Scholar](ipfs.zenpool.io)
- Work Status: I am block chain, the researchers developed a chain of digital assets and projects such as farm produce traceability chain from filecoin early testing network has been involved in testing and bug debugging, participated in the [HackFS] (https://hack.ethglobal.co/showcase/ipfs-scholar-rec8gIaA880VptIZc), in the event of a slingshot also invited to slingshot - show - and share the idea - tell activities, A large Lotus cluster real-time monitoring system is currently under development.
- Storage data set: Currently, files are mainly submitted on [IPFs-Scholar](IPFs.zenpool.io) to store astronomical data and AI training set in [Select Data set](). Currently, DataCap of 5TiB is needed to store these important data.
- Storage data: I prefer miner storage in the Greater China region. One file is stored in five copies.

**Comment by philippbanhardt** [comment]
Hey @liyue634 thanks, can you kindly

1. Add more information on yourself and any other individuals involved (i.e. links to social profiles (can also be in Chinese web))
2. Be specific about the type, source and your relationship with the data you are looking to store as a client?
3. Elaborate more on how you are intending to store the data in the network, including whether you would be OK to post here links to deal transactions?

Thanks

**Comment by liyue634** [comment]
- I am the vice president of [Digital Assets (Chongqing) Research Institute](https://www.cida.ac.cn/). I have been engaged in the research and application of blockchain and digital assets for a long time. Last year, I began to study IPFS related applications and use [WeChat Official Account](https://mp.weixin.qq.com/s/HaTooowUKn2sUR6HZUVwxA) to promote IPFS related technologies and knowledge.

- The stored data is mainly a selection of data sets provided by the official GitHub.

- I will give priority to miners in close proximity, I will backup the data, and I can make my trades public here.

**Comment by philippbanhardt** [comment]
Hi @liyue634 

- Do you have a working link to the data you are looking to store? The one you shared in one of your earlier posts here seems to be broken
- The website of the research institute does not list your name; is there any other web collateral you can share that would like your name to the institute or other social profile that is in your name?

Thanks

**Comment by liyue634** [comment]
-The data I'm going to store is mainly [data sets](https://ai.tencent.com/ailab/nlp/en/embedding.html) and some [experimental data](https://github.com/udacity/self-driving-car/tree/master/datasets), mainly from selected [data sets](https://github.com/filecoin-project/slingshot/blob/master/datasets.md)
-The researchers' information is not complete on the Digital Assets Research Institute's website.This is my [linkedin](https://www.linkedin.com/in/eric-cao-45080a202)

**Comment by philippbanhardt** [comment]
Hey @liyue634 thanks for adding additional clarity, however at this time the foundation will not be able to approve your request given various similar requests with the aim to store the same data sets (some already approved). Keep in mind that this is the policy / decision from the foundation; other notaries may employ different policies and you are free to re-apply for datacap with other notaries or with the foundation at any time. Thanks
