### ISSUE TITLE
Client Allocation Request for: Sake

### ISSUE THREAD

**Issue by Clearwine** [keyko-io/filecoin-clients-onboarding#115]
---

# Client Allocation Questions 

## Core Information
- Name: Sake
- Website / Social Media: JLcloud
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3w6jtgmfu7wewdzomdiow5kwxukscxrk2uvdfk5i3zsc6k2aa4sj53p5smasjpgyywjvrddi6fle3rap4dexa
- Notary Requested: philippbanhardt

**Comment by Clearwine** [comment]
How can I know if my application has been successful

**Comment by Clearwine** [comment]
How can I know if my application is successful and progress

**Comment by philippbanhardt** [comment]
Hey @Clearwine - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

You will be informed in this thread about the status of your application.

Thanks

**Comment by Clearwine** [comment]
Media links:http://filecoin.huala.tech/#/Landing
Participate in Slingshot phase 1 and store valuable data 8.6TiB
want to store netease mirror around 500TiB, which officially provides public data in the dataset
Upload data through LOUts

**Comment by Clearwine** [comment]
Media links:http://filecoin.huala.tech/#/Landing
Participate in Slingshot phase 1 and store valuable data 8.6TiB
want to store netease mirror around 500TiB, which officially provides public data in the dataset
Upload data through lotus

**Comment by Clearwine** [comment]
We have participated in the testing of Lotus/Filecoin since the devnet, and submitted several bug feedback and issue discussions in each version of the devnet. We are Bhero, represented by t02399 , we generated more than 7PB of power in the of the space race1&space race2, and participated in the test of slingshot 1, generating 8.6TB of data storage.

At present, based on the development results of slingshot 1, we continue to promote participation in Slingshot 2, and further combine the storage and retrieval of practical applications.

At the same time, we're working on a block-browser that's more data-driven, and we plan to have the first version ready by January, which will be more programmer-friendly and data-analytics friendly.

Recently, we also received the hard disk of Filecoin Discover, which was ordered a few months ago. We are verifying the data of the hardware, which will be completed this month.

In terms of data storage, we expect to store public and open source laboratory, medical and scientific research data as well as streaming media resources without copyright restrictions. The redundancy accounts for about 10%, which is located in several cities in eastern China.

**Comment by philippbanhardt** [comment]
Hey @Clearwine thanks, can you kindly

1. Add more information on yourself and any other individuals involved in the project? E.g. links to key social profiles or news mentions etc
2. Elaborate more on the source and your relationship with the data you are looking to store as a client, e.g. how are you sourcing it, who is maintaining it etc
3. If you were awarded data cap - would you be OK in posting here deal transactions?

Thanks

**Comment by Clearwine** [comment]
1、Add more information on yourself and any other individuals involved in the project? E.g. links to key social profiles or news mentions etc
Zhejiang Binhe Yunzhi Storage Technology (Group) Co., Ltd., headquartered in Jianggan District, Hangzhou, focuses on technology research and development and scenario application in blockchain field and distributed storage field. The company focuses on the research and development and empowerment of key technologies in blockchain field and distributed storage upstream and downstream industry chain, and provides future next-generation data storage technology services with extreme privacy, high disaster tolerance and strong security for government affairs, enterprises and individual developers. And around: IPFS distributed storage cluster server, FPGA chip independent research and development, distributed storage IDC construction and service, IPFS ecological application and other four core technology sectors to carry out technology research and development and market services.
Company homepage：http://www.binheyunzhi.com/
twitter: daoman
github: jackma112358@gmail.com
            1337515210@qq.com

2、Elaborate more on the source and your relationship with the data you are looking to store as a client, e.g. how are you sourcing it, who is maintaining it etc
Currently, there are two units cooperating with us:
The first is the Chengdu Public Security Traffic Management Bureau, from which you can get the annual traffic accidents, illegal information, driver driving age distribution, hot travel destinations, passenger flow distribution and other information;
The second is the Shenzhen Human Resources and Social Security Bureau. From them, we can get information such as pension, medical care, work injury, unemployment and maternity insurance

And the above two units will be responsible for data maintenance and update

3、If you were awarded data cap - would you be OK in posting here deal transactions?
For filecoin, the filling of valuable data involves the healthy development of the whole ecology. In order to prevent fraud, any transaction information should be open and transparent, so it is necessary for the client to display its own transaction data.

**Comment by philippbanhardt** [comment]
Hey @Clearwine , can you kindly clarify whether the data you are looking to store on behalf of the Chengdu Public Security Traffic Management Bureau and Shenzhen Bureau are

- private and encrypted data / only accessible to the above entities
- you have cleared digital rights management, i.e. can store on behalf of the above entities be virtue of a contract?

Thanks

**Comment by Clearwine** [comment]
Through further communication with the above two organizations, we are allowed to access their data, but we are not allowed to upload them to other places. However, we still have two large companies that can share some valuable data：
 
1）Greenland group
Founded on July 18th 1992 with its headquarters in Shanghai China, Greenland Group has stuck to the enterprise tenet of “Greenland, create better life” in the past 22 years and followed what the government advocates and what the market calls for, forming the current industrial distribution which features “highlight on the real estate, integrated development of relevant industries including business, finance and metro” through a two-pronged development method of industrial management and capital management and ranking the 268th place in 2014 Fortune Global 500, the 40th place of the Chinese mainland enterprises on the list. In 2014, its business operating income amounted to 402.1 billion yuan, total pre-tax profits 24.2 billion yuan and total assets 478.4 billion yuan at the year-end, of which the real estate business had a pre-sale area of 21.15 million square meters and a sum of 240.8 billion yuan, both winning the global industry champion.
2）Qiniu cloud
Qiniu cloud (Shanghai qiniu Information Technology Co., Ltd.) was established in 2011. As a well-known cloud computing and data service provider in China, qiniu cloud continues to provide massive file storage and CDN The core technologies in the fields of content distribution, video on demand, interactive live broadcast and intelligent analysis and processing of large-scale heterogeneous data are deeply invested. We are committed to driving the digital future with data technology and enabling all walks of life to enter the data age.
 
However, due to privacy, our contracts with these two organizations can not be made public. We can only send you some contract pictures in private

**Comment by philippbanhardt** [comment]
Hey @Clearwine thanks for adding additional clarity, however at this time the foundation can unfortunately not approve your request given our commitment to open / public data sets. Keep in mind that this is the policy / decision from the foundation; other notaries may employ different policies and you are free to re-apply for datacap with other notaries or with the foundation at any time. Thanks

**Comment by Clearwine** [comment]
I think my last question was wrong. The data stored by our cooperation with Greenland group and Qiniu cloud can be made public and accessible to everyone.
What I mean by privacy is the contract between us and the two companies, which can prove our cooperative relationship, but the contract is not convenient to put on it

**Comment by Clearwine** [comment]
I think the last question I answered was misinterpreted.The data we store in partnership with Greenland group and Kirin Cloud can be made public and available to everyone.
By privacy I mean the contract between us and the two companies, which can prove our partnership, but the contract is not convenient to put on it
