### ISSUE TITLE
Client Allocation Request for: [Personal or Organization Name]

### ISSUE THREAD

**Issue by jifuxiang** [keyko-io/filecoin-clients-onboarding#122]
---

# Client Allocation Questions 

## Core Information
- Name: jifuxiang
- Website / Social Media: https://mp.csdn.net/console/article?spm=1010.2135.3001.5128
- DataCap Requested: 4TiB
- Addresses to be Notarized: f1qgtktwhydjafyqtoo63ayrrzntjtaaztnmmmwtq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @jifuxiang - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
