### ISSUE TITLE
Client Allocation Request for: [chenxi]

### ISSUE THREAD

**Issue by wufeivsko** [keyko-io/filecoin-clients-onboarding#123]
# Client Allocation Questions 

## Core Information
- Name: wufei
- Website / Social Media: http://blog.sina.com.cn/u/1662458344
- DataCap Requested: 4TiB
- Addresses to be Notarized: f132avo3voj34w4ddxbevr77o4p5mdddrcxhgmfcq
- Notary Requested: philippbanhardt
-----------------------------

**Comment by philippbanhardt** [comment]
Hey @wufeivsko - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by wufeivsko** [comment]
Introduce to myself:

my social media:  https://www.linkedin.com/in/%E9%A3%9E-%E5%90%B4-726847152/
About my Github:  https://github.com/wufeivsko

I am a senior blockchain operation and maintenance developer and also the specialist of data processing filesystem, contrainers, system supervisor, etc.
I have a great intrest on Filecoin/IPFS and planning to store our chain data onto the Filecoin/IPFS network, the community that I am keeping watching on is http://ipfs.cn/.

For my working experience, I have deployed networks for ethereum and cosmos for my team project, etc. Due to the day-by-day increasing exchange transactions and big amount of contract data stored on our chain,  
there became a large requirement for data store. We are planning to put our historical data onto ipfs, and I'm planning to build my project based on my fork tree of https://github.com/wufeivsko/ipfs-webui.git.

Due to the huge amount of contract-user-data space requirement, we need about 2-6 TB disk space to save the contract data and the exchange transactions.
To us, the Filecoin should be an economical and practical solution which data handling can be elastic and scalable, also keeping privacy and security.

**Comment by philippbanhardt** [comment]
Hey @wufeivsko can you kindly clarify

1. What data you are looking to store on the network? The way I read your answer above is that you are looking to store chain data?
2. How you are intending to store the data on the network, e.g. how / which miners to select etc

Also - can you please add more information / links about yourself? Can also be in Chinese web, but the LinkedIn profile you shared has very little social reputation

Thanks

**Comment by wufeivsko** [comment]
Hi, Here is the keypoints how we interact with IPFS/Filecoin based on the questions.

1. What data we are looking to store on the network: 
     -  We aimed to store both the detailed data from user transaction( not the raw transaction from block, we unpack the trx and parsed the data and decrypt the data already)---- the data will be multiple kinds based on our system , like: some trainning trainning models' dataset collected from data-feed (some of them we treat as the payload of one transaction),  some key graphs for feature matching, also we need put some important transactions to IPFS due to we need keep some logical sequence  in our system, etc. 

2. How you are intending to store the data on the network, e.g. how / which miners to select etc
I plan to store our ipfs data with about 3 replica at least. Currently our users are located in Asia, then about the miners I'd like to choose in Asia Areas for data store testing and verifications .

Thanks.

**Comment by philippbanhardt** [comment]
@wufeivsko is the data public / non encrypted and will be accessible to everyone?

Thanks

**Comment by wufeivsko** [comment]
Yes, all transaction data are public for everyone as everyone can get the transactions. And we got the public graph from public sharing resources such from shopping web, online-public datasets,  or sharing feature data training models, etc. (which has no personal privacy sensitive data) trainning for data-feed to keep the dataset safe and available for everyone.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgzhyf2igjxzcvuchazmsadcxwhj6p7r73k2hb57ywavypgdvjyq 
#### Address 
> f132avo3voj34w4ddxbevr77o4p5mdddrcxhgmfcq
#### Datacap Allocated
> 4 TiB
