### ISSUE TITLE
Client Allocation Request for: 上海守易信息科技有限公司

### ISSUE THREAD

**Issue by NBAPLUS** [keyko-io/filecoin-clients-onboarding#124]
---

# Client Allocation Questions 

## Core Information
- Name: 上海守易信息科技有限公司
- Website / Social Media: https://www.soyitech.com/#/
- DataCap Requested: 5TTiB
- Addresses to be Notarized: f1hfihibpc23a5jvn2hhw4kjjziml3cengbxeyloi
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @NBAPLUS - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
