### ISSUE TITLE
Client Allocation Request for: Superb Express

### ISSUE THREAD

**Issue by superbexpress** [keyko-io/filecoin-clients-onboarding#126]
---

# Client Allocation Questions 

## Core Information
- Name: Superb Express
- Website / Social Media: www.superb-express.de
- DataCap Requested: 1PiB
- Addresses to be Notarized: f12bl66yqtbsg6ewbjvefinq75aykutp46iegrwji
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @superbexpress - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by philippbanhardt** [comment]
Closing this issue as the application is above the 5TiB threshold
