### ISSUE TITLE
Client Allocation Request for: Hangzhou Xun Ku technology Co., LTD

### ISSUE THREAD

**Issue by mikejunqq2020** [keyko-io/filecoin-clients-onboarding#128]
---

# Client Allocation Questions 

## Core Information
- Name: Hangzhou Xun Ku technology Co., LTD
- Website / Social Media: www.xunkukeji.com
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1fpa54bz6hfang5j3nlmk6ieqcv4kda2zcqv3r5i
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @mikejunqq2020 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by mikejunqq2020** [comment]
Hangzhou XunKu Technology Co., Ltd. is a data enabling and digital asset operation company. The company connects IOT equipment, collects and stores data through independent research and development of hardware, system platform and independent architecture cloud storage room. Through AI algorithm analysis and business auxiliary operation platform, it provides business system solutions for b-end customers. The company is committed to "enabling data, making business smarter.".
	our company website is  www.xunkukeji.com .

From 2018, our whole operational scheme consist of traceability technology, education and incentive mechanism during  prophase, metaphase and anaphase  for garbage classification solution with blockchain and IPFS technology stack. the garbage classification solution has already classified 5000 + residential areas

We have much IoT data and CCTV surveillance video for garbage classification, The blockchain technology is used to trace the source of garbage. every day we have to save more than 1TB data for garbage classification and traceability. All of data and media will be desensitization and opened to the public. We are looking for more cheaper the storage solution for our data and media .

We intend to store our data and media on Filecoin for cheaper price ,redundancy and miner preferences.

Best Regards

**Comment by philippbanhardt** [comment]
Hey @mikejunqq2020 thanks for clarifying, however the Filecoin Foundation (acting as the initial notary that you applied to for receiving datacap) is at this time not covering your use case. There will be more notaries in the very near future (you can also ask on the Filecoin Slack in the filecoin-plus channel) that may have different policies. Thanks for putting your trust into the Filecoin project!
