### ISSUE TITLE
Client Allocation Request for: Jisheng Liang

### ISSUE THREAD

**Issue by liangjisheng** [keyko-io/filecoin-clients-onboarding#130]
---

# Client Allocation Questions 

## Core Information
- Name: Jisheng Liang
- Website / Social Media: https://github.com/liangjisheng
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3sni6aszb3siob3ocej2wcerx5tldkbfq4p4si3qf677a6ybqagarp7dgckg5hp2ao2ttuwfdvqns42fykkjq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @liangjisheng - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by liangjisheng** [comment]
About myself:

CSDN: https://blog.csdn.net/liangjisheng
Github:  https://github.com/liangjisheng
Twitter: https://twitter.com/4X0QeyPrAPFJH0h/

I am blockchain developer and the specialist of technology for file system and data storage system. I am developing the application for receive deal data mining for Filecoin.

In 2020.6 I focus on IPFS and Filecoin, Now I am not contribute to the community.

All of data for my project are private, I want to storage my data to the Filecoin, and my miner can get 10X power.

And I like more low price data storage solution like filecoin for redundancy.

Thanks!

**Comment by philippbanhardt** [comment]
Hey @liangjisheng thanks for clarifying, however at this time the Filecoin Foundation (acting as the first notary and also where you applied to receive datacap from) is not covering your use case of storing private data. There may be other notaries in the very near future who will be able to accept your request. I suggest you ask on the Filecoin Slack in the filecoin-plus channel.

Also please keep in mind that self dealing is prohibited and we expect you to store awarded datacap with miners that you do not have an affiliation with.

Thanks
