### ISSUE TITLE
Client Allocation Request for: codoonhealth

### ISSUE THREAD

**Issue by zhaoleistar** [keyko-io/filecoin-clients-onboarding#131]
---

# Client Allocation Questions 

## Core Information
- Name: codoonhealth
- Website / Social Media: https://www.codoonhealth.com
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1hglr6lkwgkcqs65xgi4ukmqki6qzftgw7kcbu3i
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @zhaoleistar - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by zhaoleistar** [comment]
Hey @philippbanhardt ， i will add more information about the request：

> yourself , e.g. include links to social media / news mentions etc

I am now working at Condoon Health. I am the director of technology and algorithm in the R & D department. I have been engaged in software development and big data / AI area for more than 8 years.
Condoon Health was founded in 2017 and it located in Chengdu, China. Our company is committed to improving health problems caused by hypertension, hyperglycemia and unbalanced diet. It is a sports and diet health service platform based on AI and big data technology. We have now more than  100,000 + users in our platform.
Here is some information about our company:
[https://pitchbook.com/profiles/company/434192-95](https://pitchbook.com/profiles/company/434192-95)
[ https://www.codoonhealth.com]( https://www.codoonhealth.com)
[https://www.lieyunwang.com/archives/405465](https://www.lieyunwang.com/archives/405465)

> your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc

Because we have a large number of user generated data, we have been looking for efficient, highly available and low-cost storage services. Since 2019, we have participated in some IPFS/Distributed storage summits and  got some valuable information. We hope that the storage services provided by filecoin miners can help us solve the problem about cold data storage for users.
At the same time, we notice the filecoin plus project, which will guarantee the service effectively，and we want to be a part of the project and community.

> type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc

All the data is generated by the users. We have the data usage agreement with users. This data is used to optimize our platform services and algorithms. Data will be anonymous which is related to users info.
There are a variety of data types, including: exercise data, GPS trajectory data, body state data, diet records, photos and videos. 
Currently, it contains 50TiB data,  and  90% is cold data for AI training，statistical analysis and backup.

> how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

We select active and reputable miners according to ranking, cost, location.  Some website infos will be used as reference , such as https://filfox.info/zh, https://storage.codefi.network. 
Redundancy: 3 copies; 
Location: China (Chengdu best and other cities) 

Thank you for your attention.

**Comment by philippbanhardt** [comment]
Hey @zhaoleistar thanks. Can you kindly clarify the nature of the data, i.e. is it private / encrypted or are you storing a public (anonymous) data set on behalf of your users?

**Comment by zhaoleistar** [comment]
@philippbanhardt, we will store the public/anonymous data set,  firstly. 
Thanks.

**Comment by philippbanhardt** [comment]
@zhaoleistar great, thanks for clarifying. Are you OK posting here links to the transaction details once you have been awarded datacap?

**Comment by zhaoleistar** [comment]
> @zhaoleistar great, thanks for clarifying. Are you OK posting here links to the transaction details once you have been awarded datacap?

Of course, I will post the transaction details here.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfx2lbl3g74d4q2alwghjvghgtzgbf2n3ez4ofv2nynxviotfz7i 
#### Address 
> f1hglr6lkwgkcqs65xgi4ukmqki6qzftgw7kcbu3i
#### Datacap Allocated
> 5 TiB

**Comment by zhaoleistar** [comment]
@philippbanhardt , when i try to make my deal, i got a trouble. My Address is ledger-backend Address. When i used my ledger to make a deal,  i got a error.

> ./lotus client deal XXXX
> ERROR: failed to start deal: signing deal proposal failed: ledger can only sign chain messages

that sounds, ledger address can not suppot to make a deal, what can i do?
how can i use my  allocation datacap to store my data. 
can the datacap transfer to another address.

thx!

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 5TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs
