### ISSUE TITLE
Client Allocation Request for: Jack&Me

### ISSUE THREAD

**Issue by sghmok** [keyko-io/filecoin-clients-onboarding#132]
---

# Client Allocation Questions 

## Core Information
- Name: Jack&Me
- Website / Social Media: https://www.jackandme.io
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1w2obsyxlijx3biaswobmpa2xxojx3sf4khypupq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @sghmok - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by sghmok** [comment]
Hello, @philippbanhardt, here is my answer:

I am the product algorithm director of Jack&Me. I have been working on algorithms for more than 5 years. I used to do algorithm research at the China Academy of Advanced Technology.
We, Jack&Me, are an idle computing power integration platform that volunteers to contribute the integrated computing power to scientists and institutions in cutting-edge scientific research around the world.
We are committed to making it easy for ordinary people to contribute to cutting-edge science. At present, our integrated computing power exceeds 2TiB/day.

We first learned about IPFS/Filecoin in 2019. After the IPFS/Filecoin mainnet went live in 2020, we decided to also replace our underlying data network with the IPFS/Filecoin network.
For this reason, we have been following this project in major Filecoin browsers, official communities and GitHub, and hope to participate in it.

When we gather computing power, we will produce and deploy a large amount of data, ranging from 100KiB to 500MiB. Some of these data are intermediate data involved in calculations, and some are data calculated by algorithms. For example: when our computing power is used in the AI ​​field, we need to participate in the basic training data, and the final output is the trained AI model. Of course, both the original data and the final result data are data encrypted using our algorithm, because we need to be responsible for the data security of users who use our network.

We will choose active storage miners nearby to store our data, because Jack&Me itself is a distributed network. Globally, miners who can provide effective storage are the objects we choose to store. To further ensure data security, we will choose multiple data backups.

Thank you for your review.

**Comment by philippbanhardt** [comment]
Hey @sghmok can you kindly

- Add more information on key individuals behind Jack&Me (such as yourself), i.e. links to social profiles, news mentions etc
- Elaborate more on the nature of the data you are looking to store, i.e. is all of it encrypted and private or will you also be storing public data - what is retrieval going to look like for your system?
- Are you OK posting here links to transaction details once you have been awarded datacap?

Thanks

**Comment by sghmok** [comment]
@philippbanhardt
Sorry, the information provided earlier is not comprehensive. 

Here are some reports on the introduction and application of Jack&Me:
https://mp.weixin.qq.com/s/XzVZnWdb13fLuxf4I8maBQ
https://www.chainnode.com/post/503408
http://www.fjznews.com/html/health/1c84ff51e2a8db6ce993b659.html

The data that Jack&Me needs to store consists of the following 3 parts:
1. Raw data-this part of the data is desensitized public data;
2. Algorithm-These data need to be highly encrypted;
3. Calculation results-same as above, this part of the data is also confidential, the same needs to be highly encrypted.
In particular, for the above three types of data, we will store public data such as raw data (pictures, videos, audio, etc.) in the IPFS/Filecoin network in the early stage. When we can ensure that our encryption algorithm is absolutely secure, we will gradually store the other two types of data in the IPFS/Filecoin network.

Obviously, we are willing to post detailed transaction information here after storing the data.

Thanks.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnxmlljpjvsvz4djvvtisg6xnaa23gar2co3pztj4gswtb5no6f6 
#### Address 
> f1w2obsyxlijx3biaswobmpa2xxojx3sf4khypupq
#### Datacap Allocated
> 5 TiB
