### ISSUE TITLE
Client Allocation Request for: Deplatformer

### ISSUE THREAD

**Issue by peterVG** [keyko-io/filecoin-clients-onboarding#133]
# Client Allocation Questions 

## Core Information
- Name: Peter Van Garderen / Deplatformer
- Website / Social Media: [Deplatformer](https://deplatformer.io) / [@pjvangarderen](https://twitter.com/pjvangarderen)
- DataCap Requested: 5 TiB
- Addresses to be Notarized: f3qne2hc6e6hoki2o47urwodci3546z2govz6zjachm3yeogj6rfqyoh2xticeuwwt7rk6yfbit7xvdiukt4tq
- Notary Requested: philippbanhardt

-----------------------------

**Comment by philippbanhardt** [comment]
Hey @peterVG - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by peterVG** [comment]
Hi @philippbanhardt,

**1. add more information / context here on yourself , e.g. include links to social media / news mentions etc**

Peter Van Garderen is a well respected domain expert in the field of [digital preservation](https://en.wikipedia.org/wiki/Digital_preservation). He is widely known within the global community of heritage institutions as the founder of [Artefactual Systems Inc.](https://artefactual.com) and the creator of the free and open source [Archivematica](https://archivematica.org) digital preservation system and [AtoM](https://accesstomemory.org) archival cataloging application. These tools are used to manage the discoverability, re-usability, and trustworthiness of digital information at thousands of memory organizations worldwide.

personal website: [vangarderen.net](https://vangarderen.net)
twitter: [@pjvangarderen](https://twitter.com/pjvangarderen)
linkedin: [@petervangarderen](https://www.linkedin.com/in/petervangarderen/)
github: [@peterVG](https://github.com/peterVG?tab=overview&from=2020-10-01&to=2020-10-31)
filecoin slack: [@peterVG](https://filecoin.slack.com/)

**2. your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc**

Peter is interested in bringing IPFS & Filecoin decentralized storage to the heritage institution community as well as providing solutions that help individuals liberate their siloed social platform data onto this exciting new network. His most notable contribution to the Filecoin community is leading the [Pygate](https://pygate.tech) project which provides a Python interface to Textile's Powergate API for the Filecoin network. This project was recognized as a HackFS finalist and has seen over 5000 downloads in under six months since its launch. It has opened the world of Filecoin to the vast army of Pythonista developers.

Along with his Pygate collaboraters, Peter has launched the [Deplatformer](https://deplatformer.io) project. The objective is to provide a tool for social media users to import their walled garden content into a tool that organizes, encrypts, and stores their media on Filecoin. The Deplatformer prototype was recognized as a Gitcoin Apollo hackathon finalist. 

One of Deplatformer's long-term goals is to enable users to run AI features on their own media content. The Open Images dataset will be used for training models. Peter entered the Filecoin Slingshot competition using Open Images as his curated dataset. He created a unique [digital preservation pipeline](https://deplatformer.io/open-images/) for archiving Open Image data according to industry standards. He also extracted geodata from the images and used this to create a map-based application that won the Filecoin Slingshot competition for best application in the data science category. 

Peter continues to be active in the maintenance of Pygate and the current phases of the Slingshot competition. This is providing valuable experience and knowledge for the design of a Filecoin Management Service that is on the development roadmap for the Deplatformer project.

**3. type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc**

- Upload the entire 18TB Open Images dataset over the remaining course of the Slingshot competition. Unencrypted with an online public index linking images to CID packages.
- Upload Facebook media export packages from Deplatformer early adopters. Private and encrypted. 

**4. how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc**

- The Slingshot data packages will have up to 5 replicated copies. The Deplatformer data packages will have 3 replicated packages.
- Miner & location preference during Slingshot is affected by the current gas price and congestion issues making it difficult to finalize deals. Getting verified client status is key to viability as a Filecoin client over the next few months. 
- Miner preference will be based on price and sealing time. 
- The Deplatformer project will actually be working on a Filecoin Management Service (FMS) that will attempt to manage network and miner variability/volatility to make deal management more reliable and predictable. 
- Opportunities for offline deals will be pursued in addition to standard online deals using the Pygate/Powergate/Lotus API.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceak3ddocqjxc4odp4sg23znflxfrkj5yudxqxafqbkkljt5fzqf2g 
#### Address 
> f3qne2hc6e6hoki2o47urwodci3546z2govz6zjachm3yeogj6rfqyoh2xticeuwwt7rk6yfbit7xvdiukt4tq
#### Datacap Allocated
> 5 TiB
