### ISSUE TITLE
Client Allocation Request for: Renpeng Technology Co., Ltd

### ISSUE THREAD

**Issue by tanter** [keyko-io/filecoin-clients-onboarding#137]
---

# Client Allocation Questions 

## Core Information
- Name: Renpeng Technology Co., Ltd
- Website / Social Media: http://liveipfs.com/
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3wwkvu5jqdc32qdvqkynamkmz275m3tlvm54y6sevs3mo6fryv6oympdo6wo7wso5nufa7wbcc2gx6t5pwv7a
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @tanter - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
