### ISSUE TITLE
Client Allocation Request for: capsulemining

### ISSUE THREAD

**Issue by cjreal** [keyko-io/filecoin-clients-onboarding#138]
---

# Client Allocation Questions 

## Core Information
- Name: capsulemining
- Website / Social Media: https://capsulemining.com/
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3xb3ytcnjnregv7f2vttgszf5enaw7up4zu2cuyis32yu3qgqqxdegfxy2qrpv5p4e6zlgjo4eygo3b5jlpca
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @cjreal - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by cjreal** [comment]
I am a big fan of filecoin and a saft holder. I have been actively involved in various tests of filecoin such as: space race1, space race2, slingshot1,2, etc. Currently, I am providing 10Pib committed capacity for filecoin network, and I continue to maintain a daily growth rate of 400T, and I also help many small miners who want to participate in filecoin network construction. We now need a certain amount of datacap for testing, maybe 5Tib is too much, 1Tib is also possible, anyway, thank you for your reply. Best wishes to you.


Translated with www.DeepL.com/Translator (free version)





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Philipp Banhardt"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 晚上7:19
收件人: "keyko-io/filecoin-clients-onboarding"<filecoin-clients-onboarding@noreply.github.com&gt;; 
抄送: "擦肩而过"<792039987@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [keyko-io/filecoin-clients-onboarding] Client Allocation Request for: capsulemining (#138)





 
Hey @cjreal - thanks for your request. Can you kindly add more information / context here on:
  
yourself , e.g. include links to social media / news mentions etc
 
your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
 
type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
 
how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
  
Thanks

**Comment by philippbanhardt** [comment]
Hey @cjreal at this time the Foundation is not accepting requests for storage use cases other than public data / web3 data. Bear in mind that other notaries (when operational) may have different policies that could include your use case. Thanks
