### ISSUE TITLE
Client Allocation Request for: WinEcos

### ISSUE THREAD

**Issue by shibowe** [keyko-io/filecoin-clients-onboarding#139]
---

# Client Allocation Questions 

## Core Information
- Name: WinEcos
- Website / Social Media: 
- DataCap Requested: 1TiB
- Addresses to be Notarized: 
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @shibowe - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
