### ISSUE TITLE
Client Allocation Request for: Tung Vu

### ISSUE THREAD

**Issue by vht210** [keyko-io/filecoin-clients-onboarding#143]
---

# Client Allocation Questions 

## Core Information
- Name: Tung Vu
- Website / Social Media: www.movies.ax
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3vc3wgqhgo3yvi66yoohjmqj6gkcxn56wvomyrfibqswewxqvaytohsnmso6xywrxnha5ryjoxihtxc5jmj6a
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @vht210 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by vht210** [comment]
- yourself , e.g. include links to social media / news mentions etc
 I am a software developer located in Stockholm, Sweden. My project (www.movies.ax) is mentioned at:
https://filecoin.io/blog/slingshot-phase-1-recap/
https://youtu.be/qheNJZ1DClM?t=6617

- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
I have been participated actively in Filecoin Testnet as miner (Space Race 1 and 2), as developer (Slingshot 1 and 2).
I have received community rewards for Video category, Sling Shot 1.
Actively contribute to Slack channel for Filecoin improvement, helping other miners and developers.
Contribute to FIPs.

- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
I would like to store movie collections from Public domain movies (https://archive.org/details/publicmovies212) and Prelinger Archives (https://archive.org/details/prelinger). Which are public data, CC-licensed, with size total around 5 Tb.

- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
  I will store up to 5 replication of movies with miners across the continents.

**Comment by vht210** [comment]
@philippbanhardt  can you look and give some feedback...?  I also this data is for Slingshot competition which use curated dataset.
