### ISSUE TITLE
Client Allocation Request for: [LandsatFile]

### ISSUE THREAD

**Issue by LandsatFile20** [keyko-io/filecoin-clients-onboarding#145]
# Client Allocation Questions 

## Core Information
- Name: LandsatFile
- Website / Social Media: @LandsatFile in the Slack Channle [#slingshot ](https://app.slack.com/client/TEHTVS1L6/C01AZP8BKRQ)
- DataCap Requested: 50TiB
- Addresses to be Notarized: f3wtftfpyxqyc4geuvca72k6o7ctkn4b7urbavnlizujtrow3qtdjzzpbc4mp7z4327mkzzqnfykzm333fk6sa
- Rewards:  @slingshot 2.1. We (LandsatFile) have finished 100T Eligible Data, win 2nd place.
- SR2.1 Result Link:  [Slack link](https://filecoinproject.slack.com/archives/C01AK1J7TF1/p1608336171453800) [Rewards Doc
](https://docs.google.com/spreadsheets/d/1HSrLcJeVtFC8kiGHUGTf-kad_We40206bQJ8qdCqstg/edit)
Notary Requested: philippbanhardt
-----------------------------

**Comment by philippbanhardt** [comment]
Thanks for you request @LandsatFile20 , however at this time the individual datacap threshold is 5TiB.
