### ISSUE TITLE
Client Allocation Request for: 上海晴歌信息技术有限公司

### ISSUE THREAD

**Issue by TiDaGao** [keyko-io/filecoin-clients-onboarding#146]
---

# Client Allocation Questions 

## Core Information
- Name: 上海晴歌信息技术有限公司
- Website / Social Media: https://www.taptap.com/developer/17455
- DataCap Requested: 5TiB
- Addresses to be Notarized: f12jp4cfw7hl4wai5ga46t3bbctpmbk62var4w64i
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @TiDaGao  - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by TiDaGao** [comment]
hi

yourself , e.g. include links to social media / news mentions etc

your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc

type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc

how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keyko-io/filecoin-clients-onboarding"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 晚上10:00
收件人:&nbsp;"keyko-io/filecoin-clients-onboarding"<filecoin-clients-onboarding@noreply.github.com&gt;;
抄送:&nbsp;"铁打"<415461051@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [keyko-io/filecoin-clients-onboarding] Client Allocation Request for: 上海晴歌信息技术有限公司 (#146)





 
Hey @TiDaGao  - thanks for your request. Can you kindly add more information / context here on:
  
yourself , e.g. include links to social media / news mentions etc
 
your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
 
type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
 
how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
  
Thanks

**Comment by TiDaGao** [comment]
hi

yourself , e.g. include links to social media / news mentions etc
You can see the details about our team and project:https://www.f6s.com/farlandproject


your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
I had joined Slingshot1. My project is ipfsMart.https://github.com/filecoin-project/slingshot/blob/master/participants/ipfsMart.md

type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
Our project(farlandproject) will store all game online datas on filecoin. We store these datas in game server at past. This is an attempt we have never done before.
Every game player data, game configuration, etc., need to store some data on Filecoin. If our game reaches objective player data, it will generate several T storage data.


how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
We plan to store our data in 2~3 copies,each copy in different miner. We will store the data in miners close to Shanghai for the convenience of our first batch of users.
We will select miners in different region of Asia. As game players increase, we will choose to store data in an area close to a large number of players.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keyko-io/filecoin-clients-onboarding"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 晚上10:00
收件人:&nbsp;"keyko-io/filecoin-clients-onboarding"<filecoin-clients-onboarding@noreply.github.com&gt;;
抄送:&nbsp;"铁打"<415461051@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [keyko-io/filecoin-clients-onboarding] Client Allocation Request for: 上海晴歌信息技术有限公司 (#146)





 
Hey @TiDaGao  - thanks for your request. Can you kindly add more information / context here on:
  
yourself , e.g. include links to social media / news mentions etc
 
your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
 
type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
 
how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
  
Thanks
