### ISSUE TITLE
Client Allocation Request for: [SwiftBackup]

### ISSUE THREAD

**Issue by Cxhly091** [keyko-io/filecoin-clients-onboarding#147]
# Client Allocation Questions 

## Core Information
- Name: [ISwiftBackup Team]
- Website / Social Media: [https://cloudbackup.storswift.com/]
- DataCap Requested: [5TiB]
- Addresses to be Notarized: [f3rzs6hmpvbwb4uout7oy3klximlyyhzlrbuw5hxkuwszlqrx76njbucvpebnw6jyfpegv47emvhgotsthh42a]

-----------------------------

**Comment by philippbanhardt** [comment]
Hey @Cxhly091 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by Cxhly091** [comment]
> * We have developed applications based on IPFS/Filecoin for a long time. Please see our application: https://cloudbackup.storswift.com/.  Of course we will continue to improve it.
> * We will store public data to Filecoin， including NYC Trip Record Data, Monolith VR Materials, 163 source Dataset and some other datasets in https://github.com/filecoin-project/slingshot/blob/master/datasets.md.
> * We will save data with two or three copies to improve the availability. At first the data will be stored to Chinese mainland and HK, and later we may store data to miners in Europe, Oceania, North America because we have enterprise partners there. Miners should have enough bandwidth to receive data, and have technique supports to make sure the data availability and security.


Thanks

**Comment by Cxhly091** [comment]
> # Client Allocation Questions
> ## Core Information
> * Name: [ISwiftBackup Team]
> * Website / Social Media: [https://cloudbackup.storswift.com/]
> * DataCap Requested: [5TiB]
> * Addresses to be Notarized: [f3rzs6hmpvbwb4uout7oy3klximlyyhzlrbuw5hxkuwszlqrx76njbucvpebnw6jyfpegv47emvhgotsthh42a]

**Comment by Cxhly091** [comment]
any progress？
