### ISSUE TITLE
Client Allocation Request for: xuanxv

### ISSUE THREAD

**Issue by liusiry** [keyko-io/filecoin-clients-onboarding#148]
---

# Client Allocation Questions 

## Core Information
- Name: xuanxv
- Website / Social Media: http://fil.filestar.store/
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3vixclbeecnqffx2oohox4q6mdrm2rfm2ij2kadcgy7dkbkqbvljryp3ehxivkgij435ukofkbd2vsea56c2q
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @liusiry - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
