### ISSUE TITLE
Client Allocation Request for: 

### ISSUE THREAD

**Issue by NSC-FIL** [keyko-io/filecoin-clients-onboarding#149]
---

# Client Allocation Questions 

## Core Information
- Name: Nelson
- Website / Social Media: Slack @Nelson
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3rvnrq5mr64wpwsztyy7fj2lo5rjupm6myol4jcn7h3ffgbchzmx5gta7ki5wrmxpp45tlccmlyazaqs6tanq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @NSC-FIL - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
