### ISSUE TITLE
Client Allocation Request for: liangjisheng-6block

### ISSUE THREAD

**Issue by liangjisheng-6block** [keyko-io/filecoin-clients-onboarding#150]
---

# Client Allocation Questions 

## Core Information
- Name: liangjisheng-6block
- Website / Social Media: 
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3sni6aszb3siob3ocej2wcerx5tldkbfq4p4si3qf677a6ybqagarp7dgckg5hp2ao2ttuwfdvqns42fykkjq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @liangjisheng-6block - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
