### ISSUE TITLE
Client Allocation Request for: Nebula

### ISSUE THREAD

**Issue by kuroky916** [keyko-io/filecoin-clients-onboarding#151]
---

# Client Allocation Questions 

## Core Information
- Name: Nebula
- Website / Social Media: nebula.minerhub.com
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1arexg6wxieqh36qvbx3prlrgxt34aui7wf4w4zq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @kuroky916 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by kuroky916** [comment]
> Hey @kuroky916 - thanks for your request. Can you kindly add more information / context here on:
> 
> * yourself , e.g. include links to social media / news mentions etc
> * your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
> * type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
> * how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
> 
> Thanks

MinerHub is an innovative company that provides professional mining management systems for miners. It owns Wondermole,the world's leading Ethereum mining management system, manages more than 3million GPU cards.This  News report mentioned  us:https://blog.nebulaai.org/nebula-ai-and-chinas-largest-mining-community-minerhub/

Nebula is another product of minerhub，which is the best  filecoin  cluster solution for large and medium-sized  miners.
We have a nice technical team on IPFS, supported CreativeFileCloud project won second place in the slingshot phase 1.This video has an introduction to us:https://www.bilibili.com/video/av457590471/
Our storage  Type： files, compressed packets, images, audio, video, etc.
Size：500TB-2PB
Source：We will using all of official curated datasets, also some files uploaded by users that under Creative Commons License.
Data Relationship：We have kinds of partners. They are willing to share the files, and all the files are under Creative Commons License.
 We will  useing    Powergate to store the data to IPFS/Filecoin. Also will use lotus directly for some large files. We prefer Asian miners.


Users(Designers, Photographer, Video producers, and Creative studios etc.) upload data directly through our web client, and then we use Powergate transfer the data to the ipfs and filecoin network. Our server will record the data CID for users to search and download the data.
