### ISSUE TITLE
Client Allocation Request for: [CenttenCloud]

### ISSUE THREAD

**Issue by fengruanyijiangshui** [keyko-io/filecoin-clients-onboarding#153]
# Client Allocation Questions 

## Core Information
- Name: [CenttenCloud]
- Website / Social Media: [www.centtencloud.com]
- DataCap Requested: [5TiB]
- Addresses to be Notarized: [f1jonoi53hd7ydxtf47vqlzvnfzpyt3te5nhy4fuq]

-----------------------------

**Comment by philippbanhardt** [comment]
Hey @fengruanyijiangshui - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by fengruanyijiangshui** [comment]
We are a HK based IPFS/Filecoin operator. Our website is https://nebula.ventures.  
We will store public data to Filecoin. Currently all datasets are from https://github.com/filecoin-project/slingshot/blob/master/datasets.md. We will put more and more useful data with pulic read access in Southeast Asia to Filecoin.  In the future we may consider private data, too.  
We will use two or three copies. It's better that miners are in Asia, and has enough experience in Filecoin mining. Also they need professional support engineers.

**Comment by fengruanyijiangshui** [comment]
We are a HK based IPFS/Filecoin operator. Our website is https://nebula.ventures.&nbsp;&nbsp;
We will store public data to Filecoin. Currently all datasets are from https://github.com/filecoin-project/slingshot/blob/master/datasets.md. We will put more and more useful data with pulic read access in Southeast Asia to Filecoin.&nbsp; In the future we may consider private data, too.&nbsp;&nbsp;
We will use two or three copies. It's better that miners are in Asia, and has enough experience in Filecoin mining. Also they need professional support engineers.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keyko-io/filecoin-clients-onboarding"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 凌晨1:19
收件人:&nbsp;"keyko-io/filecoin-clients-onboarding"<filecoin-clients-onboarding@noreply.github.com&gt;;
抄送:&nbsp;"1813465200"<1813465200@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [keyko-io/filecoin-clients-onboarding] Client Allocation Request for: [CenttenCloud] (#153)





 
Hey @fengruanyijiangshui - thanks for your request. Can you kindly add more information / context here on:
  
yourself , e.g. include links to social media / news mentions etc
 
your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
 
type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
 
how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
  
Thanks

**Comment by fengruanyijiangshui** [comment]
> Hey @fengruanyijiangshui - thanks for your request. Can you kindly add more information / context here on:
> 
> * yourself , e.g. include links to social media / news mentions etc
> * your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
> * type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
> * how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
> 
> Thanks

https://github.com/filecoin-project/slingshot/blob/master/datasets.md

**Comment by fengruanyijiangshui** [comment]
> Hey @fengruanyijiangshui - thanks for your request. Can you kindly add more information / context here on:
> 
> * yourself , e.g. include links to social media / news mentions etc
> * your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
> * type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
> * how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
> 
> Thanks


We are a HK based IPFS/Filecoin operator. Our website is https://nebula.ventures.&nbsp;&nbsp;
We will store public data to Filecoin. Currently all datasets are from https://github.com/filecoin-project/slingshot/blob/master/datasets.md. We will put more and more useful data with pulic read access in Southeast Asia to Filecoin.&nbsp; In the future we may consider private data, too.&nbsp;&nbsp;
We will use two or three copies. It's better that miners are in Asia, and has enough experience in Filecoin mining. Also they need professional support engineers.
