### ISSUE TITLE
Client Allocation Request for: hexingguo 

### ISSUE THREAD

**Issue by hxg8202** [keyko-io/filecoin-clients-onboarding#154]
# Client Allocation Questions 

## Core Information
- Name: 品茗
- Website / Social Media: www.pinming.cn
- DataCap Requested: 5TB
- Addresses to be Notarized: f12yu4ceblhspcwjiirqmxf3d6bjnhczbhwowfuii

-----------------------------

**Comment by philippbanhardt** [comment]
Hey @hxg8202 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
