### ISSUE TITLE
Client Allocation Request for: Angelo Schalley

### ISSUE THREAD

**Issue by gh3990** [keyko-io/filecoin-clients-onboarding#155]
---

# Client Allocation Questions 

## Core Information
- Name: Angelo Schalley
- Website / Social Media: filecoin.eu
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1mtrb6eswkfl5tak2hqmjptornjn3du7eznwt56q
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @gh3990 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by gh3990** [comment]
@philippbanhardt , I'm going to close this case. For I'm not going to use it in this manner. Thanks
