### ISSUE TITLE
Client Allocation Request for: bjwswang

### ISSUE THREAD

**Issue by bjwswang** [keyko-io/filecoin-clients-onboarding#156]
---

# Client Allocation Questions 

## Core Information
- Name: bjwswang
- Website / Social Media: https://github.com/bjwswang
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1lszblkedtcee3kqhk7uxluit23xhn4opkzzobhi
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @bjwswang - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
