### ISSUE TITLE
Client Allocation Request for: weforu

### ISSUE THREAD

**Issue by namoo1** [keyko-io/filecoin-clients-onboarding#160]
---

# Client Allocation Questions 

## Core Information
- Name: weforu
- Website / Social Media: https://blog.naver.com/weforu
- DataCap Requested: 1TiB
- Addresses to be Notarized: f144fgghdzcb4mmw36epieolhligarygb66aqns7a
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @namoo1 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by namoo1** [comment]
I'm sending you the addition you requested.
