### ISSUE TITLE
Client Allocation Request for: psh0691

### ISSUE THREAD

**Issue by psh0691** [keyko-io/filecoin-clients-onboarding#161]
---

# Client Allocation Questions 

## Core Information
- Name: psh0691
- Website / Social Media: 
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3u5l74k5b3kh4drszygkaowx7rx3fv4pcqh7c7yn2k6xgvtdcb344v3cyfvzssropkqr7bqxnkyuhyqmoez6q
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @psh0691 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by psh0691** [comment]
- social media 
   https://band.us/band/69190040
  https://www.youtube.com/channel/UC6zgRpEUuh-_V7HUJdtpn_g/featured
  (  IPFS / Filecoin Introduction video Korean subtitles)

- filecoinproject.slack.com Activity
Publish a collection of lotus/lotus-miner commands
https://filecoinproject.slack.com/archives/CQLDFHAJY/p1607501420044100
Operating nodes from test net, 100Fil compensation the day before mainnet (f022309).

-  The data I want to save is released as a video of the Bible lecture.
http://www.jbch.org/kor/research/list.php?sCode=10r12r11r14
http://www.jbch.org/kor/research/list.php?sCode=10r12r11r15
