### ISSUE TITLE
Client Allocation Request for: John McLaughlin

### ISSUE THREAD

**Issue by georgemac510** [keyko-io/filecoin-clients-onboarding#162]
---

# Client Allocation Questions 

## Core Information
- Name: John McLaughlin
- Website / Social Media: https://mckurzcapital.com/, TWTR: @georgemac510, @mckurz
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3xd2oebvfnzbwpyuwrs5eb2upzrbjopoqttfc5kpolxruko6slpis64e3htc5yudfnfcexjny5x4rhz2rp5aq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @georgemac510 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by georgemac510** [comment]
Hi @philippbanhardt,

Please see my responses to your inquiries below:
1) **yourself , e.g. include links to social media / news mentions etc**: A bit more about me and my experiences in blockchain development can be found at my LinkedIn address, https://www.linkedin.com/in/john-mclaughlin-981989a5/ and my firm's website, https://mckurzcapital.com/. One of my two Twitter accounts, thoroughly demonstrates my dedication to blockchain development, https://twitter.com/GeorgeMac510/with_replies

2) As for Filecoin community contribution and engagement, my project https://fin-file.herokuapp.com/ was showcased by me for the "Slingshot Show and Tell" presentation on October 8, 2020; https://www.pscp.tv/w/1PlJQNPYlLWxE. My other Twitter account, https://twitter.com/mckurz/with_replies demonstrates my continuous engagement and support of the Filecoin community. I am very active in the Filecoin Slack channel where I am an active contributor in the #slingshot, #fil-lotus, #powergate-users and #fil-storage-devs channels. I have been contributing actively to the Filecoin community since the summer of 2020 when competing in the ETHGlobal Filecoin hackathon. My hack can be found at   https://hack.ethglobal.co/showcase/fin-file-recqttDK2ykFDPTVq

3) During my participation in Slingshot Space Race 1, SR2.1 and currently in SR2.2, I have been contributing to https://www.kaggle.com/georgemac510/top-100-crypto-dataset , which is a dataset that I initiated and has been added to the approved datasets list for the Slingshot competition at https://github.com/filecoin-project/slingshot/blob/master/datasets.md as the **Top 100 Crypto Investor Dataset**. This is a public dataset with non-copyrighted data which is open to anyone to contribute to. This dataset intrigues me and I will continue to build it for may ways to come as I have been involved in digital assets for 6 years and the trading of tradeable assets for over 30 years. My own contribution and maintenance of this dataset should grow it to over 100 TB's.

4) I use Textile.io Powergate and Hub as well as Lotus client through my Fin-File website https://fin-file.herokuapp.com/ to push this data to the hot storage IPFS layer, then cold storage in Filecoin. Users can use Powergate, Hub and Lotus to retrieve this valuable data for use in building digital asset investment portfolios. Our storage deals range in size from 250 MiB to 8 GiB. We do not use a redundancy factor any higher than 4 as we consider this unnecessary.  We tend to use North American and European miners such as f01278 and f08403, but recently have used miners based in China as they have been offering more reasonable pricing.

Thank you for your attention to this request.  Please let me know, if I can offer any additional information.

Best,

John McLaughlin

**Comment by georgemac510** [comment]
Hi Philipp,

I know that you are super busy, but I wanted to check on the status of my
verified deals application. I had updated my application to include the
suggested info that was needed. My username is @georgemac510.

Thanks very much.

Best,

John McLaughlin
