### ISSUE TITLE
Client Allocation Request for: Speedium

### ISSUE THREAD

**Issue by cryptowhizzard** [keyko-io/filecoin-clients-onboarding#165]
---

# Client Allocation Questions 

## Core Information
- Name: Speedium
- Website / Social Media: https://www.speedium.network
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1luelfcqktlgpw55cqsqieyilusqrayzxbctsqfa
- Notary Requested: philippbanhardt

**Comment by cryptowhizzard** [comment]
Hello, 

For the details on this request please check : https://github.com/filecoin-project/notary-governance/issues/68

**Comment by philippbanhardt** [comment]
Hey @cryptowhizzard - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by cryptowhizzard** [comment]
## Core Information
- Name: Wijnand Schouten
- (Optional) Affiliated Organization: Speedium
- Website / Social Media: https://speedium.network
- On-chain Address(es) to be Notarized: N/A
- Region of Operation: Europe
- Use case(s) to be supported: Usenet
- DataCap Requested: 100TB per quarter / 400 TB Yearly.

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Long Term Network Alignment
### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As a usenet organization, Speedium has been engaged with blockchain technology since day one. We are extremely interested in all sorts of decentralized storage and have been experimenting with multiple blockchain storage projects since 2019.
Since the launch of Filecoin we have been participating in Testnet, Spacerace 1, Spacerace 2 and Mainnet.
We have been expanding our calculating power with a setup containing more than 25 units for PC2 and 5 units for PC1 being able to seal more than 25 TiB daily on full throttle. At this moment we are looking into ways how to merge our current Usenet system with the Filecoin blockchain.
Hopefully we will be able to store multiple TiB's daily to fulfill our storage needs and serve our Speedium customers.
Usenet currently sustains a daily feed of 140 TB of data. Part of that data is populair data and frequently downloaded. We intend to cache this data onto the Filecoin chain perusing our need of decentralized storage. We are currently operating with miner ID F01240. Our GitHub handle actively participating is cryptowhizzard.
```


### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
832 FIL total under F01240.

```

## Industry Reputation
### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Please answer here.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```

In 2019, Hidde and I (aka "Hidde / Wijnand Schouten") introduced Blockchain storage on our website Speedium.network, actively promoting the possibility that it can be done. With this believe we started to be involved in the Filecoin community and have been engaging parties to join us to invest. 

Since the beginning of testnet we have filed multiple bug reports on Git.
 

```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```

Speedium ( https://speedium.network ) is the first Blockchain Usenet Platform. We operate our own fully independent backbone ( IPV4/IPV6 ) and Usenet storage.
Currently we are connected with 30 Gb/s with multiple exchanges like Speed-IX / NL-IX proving extreme low latency and high speed transfers throughout Europe.
To find more statistics on how we are connected, see peedingdb.com/net/23120. 
We are currently providing our peering partners with a combined Usenet feed of +/- 140 TB daily and we are fully storing this for over a month in our spool arrays.
We are a Dutch usenet provider and we are operating with three board members, fully operational since 2019.


```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Organisation: Speedium
Website: https://speedium.network
founded in 2019 
headquartered in Oudkarspel
Number of employees: 4
Discord: https://discord.gg/2hxXZBS
Telegram: https://t.me/speedium

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.
```


## Diversity and Decentralization
### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
N/A
```


# Allocation Plan
## Concreteness of Allocation Plan 
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We plan to support one use case of Speedium. The percentage will be determined by our knowledge and usage expectation, which may vary depending on the variable circumstances of each scenario.
- 100% Usenet storage of Speedium

```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
We intend to store files on the chain who are downloaded more than 3 times. This can be done by setting the scoring number in Diablo.
https://github.com/cryptowhizzard/diablo-speedium/blob/master/samples/dserver.hosts

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
At this moment, the address that will be allocated will have its keys secured on a hardware wallet.
```

**Comment by philippbanhardt** [comment]
Closing out this issue as we have moved to a new repo and will link there: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/31
