### ISSUE TITLE
Client Allocation Request for: bebo

### ISSUE THREAD

**Issue by sprwig** [keyko-io/filecoin-clients-onboarding#26]
---

# Client Allocation Questions 

## Core Information
- Name: bebo
- Website / Social Media: https://github.com/filecoin-project/slingshot/pull/195/files
- DataCap Requested: 2TiB
- Addresses to be Notarized: f1vwas4pwezl3fk5xelbxtjn5n2tjdhxtz62aq4ni

**Comment by philippbanhardt** [comment]
Hey @sprwig - thanks for your request. Can you please elaborate more on

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you are looking to store on Filecoin, e.g. public data vs private data etc

**Comment by philippbanhardt** [comment]
Hey @sprwig - friendly nudge on the above.
