### ISSUE TITLE
Client Allocation Request for: Protocol Labs

### ISSUE THREAD

**Issue by jnthnvctr** [keyko-io/filecoin-clients-onboarding#27]
---

# Client Allocation Questions 

## Core Information
- Name: Protocol Labs
- Website / Social Media: protocol.ai
- DataCap Requested: 1GiB
- Addresses to be Notarized: f1m7rt4hasnidwe2dqf7475fizb3mn6npur2l4egq

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcbxij6a3tyn6pw55xzqrfrtqdvm5vxdftaodpjkgjhkjeye2mbc 
#### Address 
> f1m7rt4hasnidwe2dqf7475fizb3mn6npur2l4egq
#### Datacap Allocated
> 1GiB
