### ISSUE TITLE
Client Allocation Request for: Filecoin Discover

### ISSUE THREAD

**Issue by ribasushi** [keyko-io/filecoin-clients-onboarding#28]
---

# Client Allocation Questions 

## Core Information
- Name: Filecoin Discover
- Website / Social Media: https://store.filecoin-discover.com/
- DataCap Requested: 2TiB
- Addresses to be Notarized: Multiple ( see github comments )

**Comment by philippbanhardt** [comment]
Hey @ribasushi - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by ribasushi** [comment]
Hi @philippbanhardt, please see the answers below!

> yourself , e.g. include links to social media / news mentions etc

I am a contributor at Protocol Labs, mainly working with IPLD. My Filecoin-slack handle ( like my github ) is `ribasushi`. I have been involved with and contributing to the IPFS/IPLD/Filecoin ecosystems since 2016.
I am applying on behalf of the Filecoin Discover (https://store.filecoin-discover.com/) project. It is a Protocol Labs sponsored initiative to [seed the Filecoin network with datasets important for humanity](https://aithority.com/security/the-future-of-the-data-economy-is-here-filecoin-is-live/). This project was first publicly announced in May of 2020 (https://filecoin.io/blog/intro-filecoin-discover/), with a community currently consisting of 534 participants in the #fil-discover-support slack room in the Filecoin-slack.

> your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc

Filecoin Discover is a Protocol Labs sponsored project to seed the Filecoin network with important datasets for humanity. This project was first publicly announced in May of 2020 (https://filecoin.io/blog/intro-filecoin-discover/). The aim of this project is to store petabytes of valuable data on the Filecoin network. As a result of the preparatory work, a number of useful features have been tested within the Filecoin tooling such as [offline deals](https://github.com/filecoin-project/oni/pull/173). A number of other pieces of our tooling have been open sourced as a result of this project, e.g.: https://github.com/chafey/dumbo-drop#readme

> type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc

Filecoin Discover aims to store data from a variety of categories - ranging from important cultural datasets like Project Gutenberg to mapping data to AI/ML datasets. All of these datasets are open source and public. In the future, we aim to launch a website for exploration of these datasets, enabling complete and/or partial retrieval and inspection of everything stored within the course of this program. For a full list of datasets please see: https://store.filecoin-discover.com/pages/full-dataset-list

> how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

We are storing all our datasets with high redundancy: >= 6 copies per dataset. We do this by first sourcing a set of orders per category (by enabling orders on our store), and then allocating datasets based on customer demand. Where applicable, we bias towards sending datasets to regions where there might be cultural sensitivity. During our beta-test, in order to promote decentralization, we will use this allocation of data cap to only onboard a single sector’s worth of data from each miner - as our intent is to load test starting many deals in parallel. In doing so, we aim to store a small portion of our total datasets across a large number of geographies.

On request, we can privately share more information about the geographic spread of the miners who applied to the program. As an overview we have representation of miners from over a dozen countries attempting to store Discover data.

All proposed deals under this data-cap are intended to have fast retrieval enabled, in order to facilitate the future retrieval website.

**Comment by philippbanhardt** [comment]
Thank you @ribasushi for sharing the context. You had mentioned that the requested datacap will be spent across a number of different addresses. Can you kindly share those addresses and map with an individual datacap?

**Comment by ribasushi** [comment]
@philippbanhardt apologies for the late response here. Please split evenly 512GiB each among these 4:
- `f1lq35h7sk5pdyzymnhh27ywubr7qsnu7cgcwgjla`
- `f1ozspv62aays4owiwzen2xvi22vbymkplaplxrli`
- `f3qxw65gv4fdlptz6n45aw4s6mvanpegjf3zfnsbiy5ghvuvtortxjmoc2ydrm33t2m2lmpzklkovddw6j5imq`
- `f3vmoie5eprp7hemixg6onrrpmlpsr4frmghlfnxx7fi3rxbdq4c5enpj7r2qjipxenacaijncq35oldgb7irq`

**Comment by philippbanhardt** [comment]
@ribasushi thanks, I have awarded 512 GiB for each of the above addresses.
