### ISSUE TITLE
Client Allocation Request for: wang liang

### ISSUE THREAD

**Issue by imageorbit** [keyko-io/filecoin-clients-onboarding#29]
---

# Client Allocation Questions 

## Core Information
- Name: wang liang
- Website / Social Media: imageorbit.space
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q

**Comment by philippbanhardt** [comment]
Hey @imageorbit - thanks for your request. Can you kindly add more information / context on

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by imageorbit** [comment]
* yourself , e.g. include links to social media / news mentions etc
    wang liang,www.linkedin.com/in/liang-wang-85076b47/
    10+ years experience in search engine/AI research area.
    Work  experience in Tencent, Sogou


* your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc

 Main developer of  Minerva. Minerva is a storage plugin of Apache Drill that connects IPFS's decentralized storage and Drill's flexible query engine.  Simply speaking, users could query the “content” of csv,json,… files in IPFS by standard SQL. It could be regarded as the Google BigQuery  in IPFS.  

IPFS awesome APP: https://awesome.ipfs.io/ 
GitHub:https://github.com/bdchain/Minerva
Brief introduction:https://www.slideshare.net/mobile/BowenDing4/minerva-ipfs-storage-plugin-for-ipfs
    
* type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
        
Full dataset of ImageNet. It’s a public image data set.
Our group submit it to Filecoin slingshot curated datasets and is approved.  
ImageNet: an image database organized according to the WordNet hierarchy, 1.2T, jpeg    http://www.image-net.org/

* how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Although Imagenet is one of most famous public data set, this project is rarely updated after 2016. The full data set has couldn't been downloaded from its web site. We have to download this data set by BitTorrent and origin image url.  

In fact, many other public data projects also meet this problem. 
Mostly a one-time investment. No profit model. Based on aws and other cloud platforms with dozens of TB, which has extremely high costs of download and storage.

So we think Filecoin may  provide a promising solution for public data set projects. 

We will store this dataset in different areas,  select stable miners  from https://www.storage.codefi.network/

**Comment by philippbanhardt** [comment]
Thanks @imageorbit, the information provided is very helpful. In case you already have miners in mind, can you kindly disclose any existing relationships? Thanks

**Comment by imageorbit** [comment]
. In case you already have miners in mind, can you kindly disclose any existing relationships? 

These seems still no 'really' stable miner to accept deals, especially when gas fee is very high.
In  slingshot race, I find some relatively stable miners like f060072,f021961,f010491 and talk with the owner of f021961 in slack. 
I will find more stable miners in different areas in the future.

. Also would you agree to posting here the transaction links once you have been awarded data cap + made the deal? 

Yes, of course :)

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaatcccylxlvavnxwzasajzhtitg3ncv57s3po35wru7dfym7oode 
#### Address 
> f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q
#### Datacap Allocated
> 1 TiB
