### ISSUE TITLE
Client Allocation Request for: Nebula Ai inc.

### ISSUE THREAD

**Issue by flyworker** [keyko-io/filecoin-clients-onboarding#30]
---

# Client Allocation Questions 

## Core Information
- Name: Nebula Ai inc.
- Website / Social Media: https://www.nbfspool.com/#/pool https://nbai.io 

- DataCap Requested: 50TiB
- Addresses to be Notarized: f3ufzpudvsjqyiholpxiqoomsd2svy26jvy4z4pzodikgovkhkp6ioxf5p4jbpnf7tgyg67dny4j75e7og7zeq

**Comment by philippbanhardt** [comment]
Hey @flyworker - thanks for your request. At this time, the FF is only considering data cap requests <5 TB. This is to ensure effective diligence relative to the tooling available and time. If you would like to request <5 TB, then please file a new request via the app.
