### ISSUE TITLE
Client Allocation Request for: FileDrive

### ISSUE THREAD

**Issue by mydoto** [keyko-io/filecoin-clients-onboarding#33]
---

# Client Allocation Questions 

## Core Information
- Name: FileDrive
- Website / Social Media: http://filedrive.io
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3wgfwtrs5p6jrkwfl2mksqa2ivgbgdjjrhjbefy3n7qzvotc3y6sazmp5gfyj7um6jlgdvlbiepzawnc6wxtq

**Comment by philippbanhardt** [comment]
Hey @mydoto - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by mydoto** [comment]
l  yourself , e.g. include links to social media / news mentions etc
FileDrive is a open source databank powered by IPFS/Filecoin, users can retrieve any data by filename or content hash.
Our team is composed of talents with years development experience. We have self-developed underlying codes, and technical architecture and solutions of distributed storage.
Team website: https://honghupro.com
Project website: http://filedrive.io
Github: https://github.com/mydoto

l  your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
(1)     Participating in Slingshot Phase 2 with over 300 TiB data
(2)     Participated in Slingshot Phase 1 by Protocol Labs: totally earned 6,885FIL o
①    Storage Awards: 6,335FIL
②    Community Choice Awards: Personal User Storage(Thrid Place) 500FIL
③    Booster Award: 50FIL
(3)     Startup project: DriveUp
①    Cloud storage application based on IPFS
②    Self-developed by FileDrive team

l  type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
Public data: open source data on the list of Filecoin slingshot curated datasets

l  how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
Redundancy: at least 3 copies
Location: intend to store data in different regions
Miner: have great reputation and contribution in Filecoin Community, or are willing to participate in the test of Fil-plus, and also consider to select miners from https://www.storage.codefi.network

**Comment by philippbanhardt** [comment]
Hey @mydoto - thanks for providing the additional information. Two more items:

- Can you share more info on the individuals behind your team? The team page on your website doesn't list names. E.g. links to social profiles would be great, if you can
- Would you be OK with posting here links to the deal transactions after receiving data cap?

Thanks

**Comment by mydoto** [comment]
Hey @philippbanhardt - here are my answers.
Q1:
Feng Li: founder of FIleDrive
Linked: https://www.linkedin.com/in/felixlee20190908/?locale=zh_CN)

Q2:
We would like to post deal transactions here.

Thanks

**Comment by philippbanhardt** [comment]
Hey @mydoto thanks. Do you have any stronger profile information (can also be on Chinese websites) you can share on the individuals? I.e. the LinkedIn profile you had shared doesn't seem to be very active / have a meaningful social graph - however I appreciate that this may be because it is a Western site.

**Comment by mydoto** [comment]
Hey @philippbanhardt .  Sorry for forgetting to share the Github profile to you. Since Li is a developer, he is really not so active on social media. Hope his Github profile can present more information about him.
Feng Li on Github: https://github.com/beeleelee

**Comment by philippbanhardt** [comment]
Hey @mydoto apologies for the long process, but are there any other profiles, web posts (can also be in Mandarin) that have a meaningful history (e.g. have been around for more than just a few months). Also pointers to any contributions to the broader Filecoin / crypto community would be helpful (e.g. a link to Slack discussions). Thanks!

**Comment by mydoto** [comment]
Hey @philippbanhardt 
 
I really understand the reason why you want more information more about both FileDrive and my team, so please don’t be apologize.
Please let me show you more thing about who we are and what we are doing right now.
 
 
About FileDrive
FileDrive team has been in Filecoin ecosystem from 2019, and conscientiously concentrate on development distributed storage solution. Our vision is to build a data transaction platform on Filecoin Network.
In 2019, we independently developed DriveUp, which is a cloud storage application based on IPFS. However, since multiple reasons we had no choice but shut down this program.
 
 
In September 2020, we participated in Slingshot Phase 1. Through hard work by all team members, finally we reached a great achievement.
SR2 Slingshot Competition Phase 1 by Protocol Labs: totally earned 6,885FIL reward
①    Storage Awards(Third Place): 6,335FIL
②    Community Choice Awards: Personal User Storage(Third Place) 500FIL
③    Booster Award: 50FIL
 
 
Now, FileDrive is ranked first in Slingshot Phase 2 with over 260 TiB data.
https://slingshot.filecoin.io/
 
 
At the same time, we have applied for Filecoin Frontier Accelerator, and became one of the top 39 teams for the final interview stage.
 
 
About data source
All of the data on FileDrive are useful and valid, and from public datasets, which are on the list of Filecoin Slingshot curated datasets.
Here are PR links:
https://github.com/filecoin-project/slingshot/pull/365/commits/7857b7626d00108974af85676a1c8b55d12307a1
https://github.com/filecoin-project/slingshot/pull/364/commits/c14d4cc0012196ed8dce6d0f78e0602cb351d2fc
 
 
About web post
Slack: @flytosky @Laura Ren
Laura and I are in Filecoin Project channels. Welcome to message us on Slack.
Most of our team members are developers, they do not have much web post about themselves and their history. If you need, I can send their CV to you in private.
 
Thanks

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfsdyxme44t6girfmvuz5grym57d6inlduqrn6zeihtamojjpbbq 
#### Address 
> f3wgfwtrs5p6jrkwfl2mksqa2ivgbgdjjrhjbefy3n7qzvotc3y6sazmp5gfyj7um6jlgdvlbiepzawnc6wxtq
#### Datacap Allocated
> 5 TiB
