### ISSUE TITLE
Client Allocation Request for: IPFS-scholar

### ISSUE THREAD

**Issue by liyue634** [keyko-io/filecoin-clients-onboarding#35]
---

# Client Allocation Questions 

## Core Information
- Name: IPFS-scholar
- Website / Social Media: ipfs.zenpool.io/ipfssteam@163.com
- DataCap Requested: 100TiB
- Addresses to be Notarized: f25zkoqxmmmvnm5fq7txkirtpfj7xmzqoo2p6763y

**Comment by philippbanhardt** [comment]
Hey @liyue634 - thanks for your request. At this time, the FF is only considering data cap requests <5 TB. This is to ensure effective diligence relative to the tooling available and time. If you would like to request <5 TB, then please file a new request via the app.
