### ISSUE TITLE
Client Allocation Request for: [Firefly ]

### ISSUE THREAD

**Issue by Firefly2020-cloud** [keyko-io/filecoin-clients-onboarding#36]
# Client Allocation Questions 

## Core Information
- Name: Firefly
- Website / Social Media:http://fireflyblock.com
- DataCap Requested: [50T]
- Addresses to be Notarized: [f1dbpdc56q6wfcmb4p2ppzqruufiqcr2s5xqwybma]

-----------------------------

**Comment by philippbanhardt** [comment]
Hey @Firefly2020-cloud - thanks for your request. At this time, the FF is only considering data cap requests <5 TB. This is to ensure effective diligence relative to the tooling available and time. If you would like to request <5 TB, then please file a new request via the app.

**Comment by Firefly2020-cloud** [comment]
Name: Firefly
Website / Social Media:http://fireflyblock.com
DataCap Requested: [5T]
Addresses to be Notarized: [f1dbpdc56q6wfcmb4p2ppzqruufiqcr2s5xqwybma]
