### ISSUE TITLE
Client Allocation Request for: NBFS Canada

### ISSUE THREAD

**Issue by flyworker** [keyko-io/filecoin-clients-onboarding#38]
# Client Allocation Questions 

## Core Information
- Name: NBFS Canada
- Website / Social Media: 
https://www.nbfspool.com/#/poo
https://nbai.io
https://twitter.com/nebula_ai
https://www.youtube.com/channel/UCWltsUAyiser4-_eLLGmpdg
- DataCap Requested: 5Tb
- Addresses to be Notarized:   f3ufzpudvsjqyiholpxiqoomsd2svy26jvy4z4pzodikgovkhkp6ioxf5p4jbpnf7tgyg67dny4j75e7og7zeq 

-----------------------------

**Comment by philippbanhardt** [comment]
Hey @flyworker - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by flyworker** [comment]
-    NBFS Canada is a Filecoin mining brand owns by Nebula AI inc.

https://www.nbfspool.com/
https://nbai.io
https://www.cengn.ca/nebula-ai/
https://www.youtube.com/channel/UCWltsUAyiser4-_eLLGmpdg
https://twitter.com/nbfscanada
https://zhuanlan.zhihu.com/p/38305056

-    History working on IPFS / Filecoin
Contributor to Calibration/SR1/SR2/Slingshot and multiple slack community champion
Integrate IPSF/Filecoin into GPU cloud computing platform Orion deep learning

-     Type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data 
-     how you intend to store the data on Filecoin,
We using ceph and raid for data redundancy. Our current data center based in Montreal Canada , and Chinain two locations with 4 miner ids , f02401,f02381,f01276,f019104, f030335

**Comment by philippbanhardt** [comment]
Hey @flyworker - thanks for providing the additional information. Few more items:

1. Can you share more info on the individuals behind your team? The team page on your website doesn't list names. E.g. links to social profiles would be great, if you can
2. Type and source of the data  you are looking to store with the data cap
3. Would you be OK with posting here links to the deal transactions after receiving data cap?

Thanks

**Comment by flyworker** [comment]
> * pe and source of the data  you are looking to store with the data cap
> 
> * Would you be OK with posting here links to the deal transactions after receiving data cap?

HI  Philip,
1. for people behind the team, you can find our company's team profile here
https://www.linkedin.com/company/nebula-ai/people
CEO Charles Cao
https://www.linkedin.com/in/charles-cao-09a79526/

COO Rex Miller
https://www.linkedin.com/in/rexhold/

Other members include the developers, architect,  Devops and QAs 
2. Type and source of the data you are looking to store with the data cap

We want to save the AI related dataset since we are an AI cloud computing company with lots of colaberation with universities and institutions, we have projects working with McGill and Concordia Universities, some grant reward by Canadian government can be found here https://www.nserc-crsng.gc.ca/ase-oro/Details-Detailles_eng.asp?id=650691

3. Would you be OK with posting here links to the deal transactions after receiving data cap?
Yes,no problem.

**Comment by philippbanhardt** [comment]
Thanks @flyworker . What is the address that you want the data cap to be awarded to?

**Comment by flyworker** [comment]
Is the address the owner key of the node?

**Comment by philippbanhardt** [comment]
It is the public address of whatever is your client

**Comment by flyworker** [comment]
> It is the public address of whatever is your client

OK ,My address is f3wg37bcd4pkioiat6634wcw4pzsxvh23nyk4irwpkl6il2vcihybr52r7gl24t77ptjulpy7sbjluwmvgdcfa

**Comment by flyworker** [comment]
> It is the public address of whatever is your client

f3ufzpudvsjqyiholpxiqoomsd2svy26jvy4z4pzodikgovkhkp6ioxf5p4jbpnf7tgyg67dny4j75e7og7zeq

**Comment by philippbanhardt** [comment]
The above address has been verified with 5TiB of data cap.
