### ISSUE TITLE
Client Allocation Request for: NUIIUN

### ISSUE THREAD

**Issue by TheGreatest-7** [keyko-io/filecoin-clients-onboarding#41]
---

# Client Allocation Questions 

## Core Information
- Name: NUIIUN
- Website / Social Media: 
- DataCap Requested: 1MiB
- Addresses to be Notarized:

**Comment by philippbanhardt** [comment]
Hey @TheGreatest-7 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
