### ISSUE TITLE
Client Allocation Request for: Starry sky in Yunnan

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [keyko-io/filecoin-clients-onboarding#42]
---

# Client Allocation Questions 

## Core Information
- Name: Starry sky in Yunnan
- Website / Social Media:  http://hlmxy.file123.pro:9006
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3qqttrr5b6df5kjrtt6fwy3bafthqboe3aeghhqas2qiwavlxjlbdmo5xsai4s5hnam53pdiq55wsvkf52s6q

**Comment by philippbanhardt** [comment]
Hey @IPFS-grandhelmsman  - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by IPFS-grandhelmsman** [comment]
- Helmsman Team；IPFS-grandhelmsman；grandhelmsman 

  https://twitter.com/Helmsma07094671

  https://twitter.com/grandhelmsman

  http://www.grandhelmsman.com/

- Participated in Trusted Setup Ceremony Phase 1 https://github.com/arielgabizon/perpetualpowersoftau/blob/master/README.md

  Participate in the first phase of the testnet that started in December 2019, ID: t019125, and the final storage capacity exceeds 1PiB

  PB-scale Miner Testing,E-mail submitted the relevant test plan,the email was sent to the Filecoin team, and Filecoin team members like @why @keren knew about it https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-pbscale-miner-testing.md

  Selected as a member of Filecoin Security Research Fellowship by Filecoin team,@why is one of the organizers, he can prove it https://security.filecoin.io/

  Participated in Trusted Setup Ceremony Phase 2 https://filecoin.io/blog/trusted-setup-complete/

  Participate in HackFS, the project is called Filecoin123 https://hack.ethglobal.co/showcase/filecoin123-recBa27E4zfpHRRln

  space race Participated in Space Race, and finally ranked 22nd in the world (name: Five Star-Helmsman&Heiben) Miner ID: t03176 https://spacerace.filecoin.io/

  Participated in the slingshot competition, project name: 1. Starry sky in Yunnan 2. Filecoin-Crawl

   Participated in Slingshot-Phase 1 Closing Ceremony https://www.youtube.com/watch?v=qheNJZ1DClM&list=PL_0VrY55uV19nu6orLLCaGCGocsjvpiGZ&index=1

  Participated in Filecoin Devgrants and submitted three application project applications:

  ·FileWallet-Tools https://github.com/filecoin-project/devgrants/pull/107

  ·Filecoin-file-storage-and-retrieval-utility https://github.com/filecoin-project/devgrants/pull/106

  ·Filecoin123-Block-Explorer https://github.com/filecoin-project/devgrants/pull/105

   PB-scale Miner Testing,E-mail submitted the relevant test plan,the email was sent to the Filecoin team, and Filecoin team members like @why @keren knew about it https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-pbscale-miner-testing.md

   Participate in HackFS, the project is called Filecoin123 https://hack.ethglobal.co/showcase/filecoin123-recBa27E4zfpHRRln

- We plan to store public data sets. Before that, we participated in the first phase of slingshot. Our project Starry sky in Yunnan stored public astronomical data, so this time we will store these public astronomical data sets https://github.com/filecoin-project/slingshot/blob/master/datasets.md

- The underlying storage system is based on erasure codes to ensure that the underlying storage is safe and reliable. We can provide storage space for all storage needs, and users can store multiple copies.

  Our node is in Shenzhen, China, miner ID: f021870

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedoefn6abkjzwgv7bxfjvy6nizcpb3j4ucfljiqordnxpxuaf3hkq 
#### Address 
> f3qqttrr5b6df5kjrtt6fwy3bafthqboe3aeghhqas2qiwavlxjlbdmo5xsai4s5hnam53pdiq55wsvkf52s6q
#### Datacap Allocated
> 5 TiB

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 5TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs
