### ISSUE TITLE
Client Allocation Request for: CoffeeDog

### ISSUE THREAD

**Issue by fondy555** [keyko-io/filecoin-clients-onboarding#43]
---

# Client Allocation Questions 

## Core Information
- Name: CoffeeDog
- Website / Social Media: http://louts.cc
- DataCap Requested: 50TiB
- Addresses to be Notarized: f3rtdgzkgl64zvk67pjecnh7gxeq67ghqtkdtksivap3gxv7heemya5qsukjhc4p4a2masawt6yrjoy6ssvmtq

**Comment by philippbanhardt** [comment]
Hey @fondy555 - thanks for your request. At this time, the FF is only considering data cap requests <5 TiB. This is to ensure effective diligence relative to the tooling available and time. If you would like to request <5 TiB, then please file a new request via the app.
