### ISSUE TITLE
Client Allocation Request for: Interstellar Infinity

### ISSUE THREAD

**Issue by LenaW983** [keyko-io/filecoin-clients-onboarding#44]
---

# Client Allocation Questions 

## Core Information
- Name: Interstellar Infinity
- Website / Social Media: http://www.wuipfs.com/
- DataCap Requested: 5PiB
- Addresses to be Notarized: f3q23pd3vwgs557rbalzsp2b4artwwrexohjyckdwjrw4g5pzen7wjez4fyqiqvp6kxwnna2ar7hubdkvzazza

**Comment by philippbanhardt** [comment]
Hey @LenaW983 - thanks for your request. At this time, the FF is only considering data cap requests <5 TiB. This is to ensure effective diligence relative to the tooling available and time. If you would like to request <5 TiB, then please file a new request via the app.
