### ISSUE TITLE
Client Allocation Request for: Neo Beat

### ISSUE THREAD

**Issue by ROXtiGerf** [keyko-io/filecoin-clients-onboarding#45]
---

# Client Allocation Questions 

## Core Information
- Name: Neo Beat
- Website / Social Media: http://www.impool.com/NeoBeat 
- DataCap Requested: 32GiB
- Addresses to be Notarized: f3uqb2gqegru5ycchufy6gyjbpiu3dk3tx4nk45aua6wd6krbvkxyj6qapu6kkicm7nyzpdpg22clgwwy2wwba

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvhqevbum6qig6nuvm4doizs7f2gx2uzm4wsya2xncoc5l3hgheu 
#### Address 
> f3uqb2gqegru5ycchufy6gyjbpiu3dk3tx4nk45aua6wd6krbvkxyj6qapu6kkicm7nyzpdpg22clgwwy2wwba
#### Datacap Allocated
> 34 GiB
