### ISSUE TITLE
Client Allocation Request for: CoffeeDog

### ISSUE THREAD

**Issue by fondy555** [keyko-io/filecoin-clients-onboarding#46]
---

# Client Allocation Questions 

## Core Information
- Name: CoffeeDog
- Website / Social Media: http://louts.cc
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3rtdgzkgl64zvk67pjecnh7gxeq67ghqtkdtksivap3gxv7heemya5qsukjhc4p4a2masawt6yrjoy6ssvmtq

**Comment by philippbanhardt** [comment]
Hey @fondy555  - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
