### ISSUE TITLE
Client Allocation Request for: 湖南蓝色风暴信息科技有限公司

### ISSUE THREAD

**Issue by KathrynWangyui** [keyko-io/filecoin-clients-onboarding#51]
---

# Client Allocation Questions 

## Core Information
- Name: 湖南蓝色风暴信息科技有限公司
- Website / Social Media: www.hnbluestorm.com
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1pq6r3iqi3yqtnka7de2bp22tl7bq6astl7oin5i
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @KathrynWangyui  - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by KathrynWangyui** [comment]
Dear&nbsp;&nbsp;Philipp,




Here is our information:

Our company&nbsp; :www.hnbluestorm.com




I always answer questions of the community ,and I&nbsp;often store data on IPFS；




I am also a Chinese miner.











&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keyko-io/filecoin-clients-onboarding"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 下午5:26
收件人:&nbsp;"keyko-io/filecoin-clients-onboarding"<filecoin-clients-onboarding@noreply.github.com&gt;;
抄送:&nbsp;"王玉"<291883623@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [keyko-io/filecoin-clients-onboarding] Client Allocation Request for: 湖南蓝色风暴信息科技有限公司 (#51)





 
Hey @KathrynWangyui  - thanks for your request. Can you kindly add more information / context here on:
  
yourself , e.g. include links to social media / news mentions etc
 
your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
 
type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
 
how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
  
Thanks
