### ISSUE TITLE
Client Allocation Request for: 安徽六六六科技有限公司

### ISSUE THREAD

**Issue by Alice1475** [keyko-io/filecoin-clients-onboarding#52]
---

# Client Allocation Questions 

## Core Information
- Name: 安徽六六六科技有限公司
- Website / Social Media: huishangyanxishe.com
- DataCap Requested: 1TiB
- Addresses to be Notarized: f14ew4fybr3grirbaii2yj4mmfo77kpayu74xegbi
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @Alice1475  - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by Alice1475** [comment]
Dear Philipp,

Here is our information:

Our company :https://aiqicha.baidu.com/company_detail_25972156332156?rq=ef&pd=ee&from=ps
I always answer questions of the community from time to time and store many public data in IPFS
Web 3.0 public data
To several miners in China



Best regards,
 
发件人： Philipp Banhardt
发送时间： 2020-11-30 17:27
收件人： keyko-io/filecoin-clients-onboarding
抄送： Alice1475; Mention
主题： Re: [keyko-io/filecoin-clients-onboarding] Client Allocation Request for:  (#52)
Hey @Alice1475 - thanks for your request. Can you kindly add more information / context here on:
yourself , e.g. include links to social media / news mentions etc
your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
Thanks

**Comment by philippbanhardt** [comment]
@Alice1475 thank you - however can you kindly expand on your answers, e.g. add key social links to the individuals behind your company and also point towards the web 3 data sets you are looking to store? We would also appreciate any pointers to community contributions (e.g. Slack or publications in your name etc)

**Comment by Alice1475** [comment]
Hi Philip,
Official account: 徽商研习社
Website: huishangyanxishe.com
TikTok: 徽品会、特产安徽
Data:
Huishang Study Course
The MCN organization of Hui Pin Hui is responsible for the short video live broadcast with goods, and its Douyin accounts include: Specialty Anhui, Hui Pin Hui, MS Mei, You Wan and more than 10 other accounts with 500W + fans on the whole network.



------------------------------------------------------------------
发件人：Philipp Banhardt <notifications@github.com>
发送时间：2020年12月2日(星期三) 03:35
收件人：keyko-io/filecoin-clients-onboarding <filecoin-clients-onboarding@noreply.github.com>
抄　送：蔡琦 <caiqi@tianrukj.com>; Mention <mention@noreply.github.com>
主　题：Re: [keyko-io/filecoin-clients-onboarding] Client Allocation Request for: 安徽六六六科技有限公司 (#52)

@Alice1475 thank you - however can you kindly expand on your answers, e.g. add key social links to the individuals behind your company and also point towards the web 3 data sets you are looking to store? We would also appreciate any pointers to community contributions (e.g. Slack or publications in your name etc)

**Comment by philippbanhardt** [comment]
Hi @Alice1475 - can you kindly expand on the information provided above? E.g. what is your relationship with Huishang University; add links to social profiles from the individuals involved; link to where the data is hosted today

Thanks

**Comment by Alice1475** [comment]
Hi Philipp,
Sorry for the late reply, I am out of business yesterday.

We created Huishang University.

Also the WeChat social media platform I created: 徽商研习社



Best regards,
蔡琦 Alice Cai
 
发件人： Philipp Banhardt
发送时间： 2020-12-02 23:01
收件人： keyko-io/filecoin-clients-onboarding
抄送： Alice1475; Mention
主题： Re: [keyko-io/filecoin-clients-onboarding] Client Allocation Request for: 安徽六六六科技有限公司 (#52)
Hi @Alice1475 - can you kindly expand on the information provided above? E.g. what is your relationship with Huishang University; add links to social profiles from the individuals involved; link to where the data is hosted today
Thanks

**Comment by Alice1475** [comment]
Hi Philipp,
Sorry for the late reply, I am out of business yesterday.

We created Huishang University. It is for people to learn the technology.

For social media, here is the WeChat social media platform I created: 徽商研习社



Best regards,

 
发件人： Philipp Banhardt
发送时间： 2020-12-02 23:01
收件人： keyko-io/filecoin-clients-onboarding
抄送： Alice1475; Mention
主题： Re: [keyko-io/filecoin-clients-onboarding] Client Allocation Request for: 安徽六六六科技有限公司 (#52)
Hi @Alice1475 - can you kindly expand on the information provided above? E.g. what is your relationship with Huishang University; add links to social profiles from the individuals involved; link to where the data is hosted today
Thanks

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaax72xaene43y7ab2djyz5vdkapohuugpr6gpirgoniztsl3mvfc 
#### Address 
> f14ew4fybr3grirbaii2yj4mmfo77kpayu74xegbi
#### Datacap Allocated
> 1 TiB
