### ISSUE TITLE
Client Allocation Request for: Suzhou Paipaitao Information Technology Co., Ltd

### ISSUE THREAD

**Issue by NBAPLUS** [keyko-io/filecoin-clients-onboarding#54]
---

# Client Allocation Questions 

## Core Information
- Name: Suzhou Paipaitao Information Technology Co., Ltd
- Website / Social Media: www.taopaipai.com
- DataCap Requested: 100TiB
- Addresses to be Notarized: f1g3jdihzsfldw3byfee627f7uyapg7gwwadorgsq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @NBAPLUS - at this time the Filecoin Foundation is only considering data cap requests < 5TB. If you wish to request a lower data cap, then please make a new request via the app.

Thanks
