### ISSUE TITLE
Client Allocation Request for: The bigdata application case research center

### ISSUE THREAD

**Issue by 0xffee** [keyko-io/filecoin-clients-onboarding#57]
---

# Client Allocation Questions 

## Core Information
- Name: The bigdata application case research center
- Website / Social Media: https://www.huodongxing.com/org/380618161547
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1yjo5zhrovw45zvmhu4ze7ve3dw6wvfouyirdggi
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @0xffee - at this time the Filecoin Foundation is only considering data cap requests <5TB. If you wish to request a lower data cap, then please make a new request via the app.

Thanks
