### ISSUE TITLE
Client Allocation Request for: 北京中电博顺智能设备技术有限公司

### ISSUE THREAD

**Issue by qingshui-wang** [keyko-io/filecoin-clients-onboarding#58]
---

# Client Allocation Questions 

## Core Information
- Name: 北京中电博顺智能设备技术有限公司
- Website / Social Media: www.bosonrobotics.com
- DataCap Requested: 160TiB
- Addresses to be Notarized: f1uhubdateuntjmpje6yg4dwy6p5hjwxewuddueiy
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @qingshui-wang - at this time the Filecoin Foundation is only considering data cap requests <5TB. If you wish to request a lower data cap, then please make a new request via the app.

Thanks

**Comment by qingshui-wang** [comment]
好吧，那我就先申请5T，希望以后能根据业务性质，申请到更大的

发自我的iPhone
