### ISSUE TITLE
Client Allocation Request for: TopX Lab

### ISSUE THREAD

**Issue by 2019jack** [keyko-io/filecoin-clients-onboarding#59]
---

# Client Allocation Questions 

## Core Information
- Name: TopX Lab
- Website / Social Media: 
- DataCap Requested: 2PiB
- Addresses to be Notarized: https://filfox.info/en/address/f020940
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @2019jack - at this time the Filecoin Foundation is only considering data cap requests <5TB. If you wish to request a lower data cap, then please make a new request via the app.

Thanks

**Comment by 2019jack** [comment]
@philippbanhardt ok, now me renew request
