### ISSUE TITLE
Client Allocation Request for: TopX Lab

### ISSUE THREAD

**Issue by 2019jack** [keyko-io/filecoin-clients-onboarding#61]
---

# Client Allocation Questions 

## Core Information
- Name: TopX Lab
- Website / Social Media: 
- DataCap Requested: 5TiB
- Addresses to be Notarized: https://filfox.info/en/address/f020940
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @2019jack - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
