### ISSUE TITLE
Client Allocation Request for: Pinata

### ISSUE THREAD

**Issue by obo20** [keyko-io/filecoin-clients-onboarding#62]
---

# Client Allocation Questions 

## Core Information
- Name: Pinata
- Website / Social Media: https://pinata.cloud
- DataCap Requested: 5TiB
- Addresses to be Notarized: f17kamajrdzjcjzj6b3y2ovc64kc7qxvkbx2dzvza
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @obo20 - thanks for you request. I know we know each other well and Pinata is a highly respected collaborator in the Filecoin ecosystem, however for sake of process and transparency: can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by obo20** [comment]
sure thing! I wasn't how much information you were looking for as part of the application process.

Myself: CTO of Pinata ( an IPFS pinning service ). 

Some notable social media links of ours:
* Twitter: https://twitter.com/IPFSPinata
* Blog: https://medium.com/pinata
* Email: team@pinata.cloud
* News mention: https://twitter.com/Filecoin/status/1319372971685838849?s=20

History: We've been working with IPFS for about 3 years now and have been running Pinata for most of that time. Pinata offers our users an easy, user friendly way to store data on decentralized storage networks. Our biggest contribution is most likely our blog series that I linked above. We've placed a lot of importance around education and want to continue educating the community by sharing all the things we've learned while building on IPFS / Filecoin. Right now our services are purely IPFS based, but we've been working on a Filecoin integration for a few months now.

Type and source of the data: The data we're looking to store on filecoin will be snapshots of our users' IPFS pinsets. Essentially we'll give users the ability to take a snapshot of their pinset at any point in time and back it up to filecoin for 6 months.

How we intend to store the data on Filecoin: Right now we're planning on just storing to one miner (until we get that perfected and then will move to multiple miners). We have a preference for miners in NA / EU.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2m3npowgmz42s5lakwmdjh5lwc5ignbrgzqpcs5owsv23evdvv6 
#### Address 
> f17kamajrdzjcjzj6b3y2ovc64kc7qxvkbx2dzvza
#### Datacap Allocated
> 5 TiB
