### ISSUE TITLE
Client Allocation Request for: askender

### ISSUE THREAD

**Issue by askender** [keyko-io/filecoin-clients-onboarding#63]
---

# Client Allocation Questions 

## Core Information
- Name: askender
- Website / Social Media: https://github.com/askender
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3uvwjknloel3zcmjrgrbmgqwp3c32l7b7tyoqj7p7njb3c2xmex6dh2jzz45a6smzqvhw53nbng2zn2p7ciza
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @askender - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by askender** [comment]
### yourself , e.g. include links to social media / news mentions etc
- https://www.linkedin.com/in/askender-li-27059265/
- https://scholar.google.com/citations?user=tzIrta0AAAAJ&hl=zh-CN   my papers
- https://twitter.com/askender43

### your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- Actively participating and helping the Filecoin miner community (more than 1k messages on slack)
- Participating to HackFS/ SR1 / SR2 Orbital burn / Slingshot 1 (project Anwen-Web3-Content-Community) / program
- report bugs and other issues: https://github.com/filecoin-project/lotus/issues/created_by/askender
- Make pull-request:  https://github.com/filecoin-project/rust-fil-proofs/pull/1253#pullrequestreview-463834037
- https://github.com/filecoin-project/lotus/pulls/askender strange, my unmerged PR is disappeared (magik6k told me he wrote a better version).
- Filecoin Slingshot community call-out award winner.

### type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- I will store public data, such as Filecoin Discover data, Slingshot Pharse 2 datasets, other Creative Commons dataset.
- I will help store user generated data already stored in IPFS. Such as ipfs data on http://matters.news/

### how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
- I will store the data on Filecoin(with fast retrieve) and IPFS both. My miner is located in China.  I prefer public data.

**Comment by philippbanhardt** [comment]
Thanks @askender - are you OK posting here the links to the deal transactions once awarded data cap? Also please keep in mind that we want to foster decentralization, so would expect you to redundantly across several miners (who are not affiliated with you also).

**Comment by askender** [comment]
> are you OK posting here the links to the deal transactions once awarded data cap? 
Yes. I'm totally ok with that.
> Also please keep in mind that we want to foster decentralization, so would expect you to redundantly across several miners (who are not affiliated with you also).
I will do that as well.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6pxmbucdux5iz5wnij5vcctrnu7z7fapnkdbjdcfp7pwcf7f3k6 
#### Address 
> f3uvwjknloel3zcmjrgrbmgqwp3c32l7b7tyoqj7p7njb3c2xmex6dh2jzz45a6smzqvhw53nbng2zn2p7ciza
#### Datacap Allocated
> 5 TiB
