### ISSUE TITLE
Client Allocation Request for: Suzhou Paipaitao Information Technology Co.,Ltd

### ISSUE THREAD

**Issue by NBAPLUS** [keyko-io/filecoin-clients-onboarding#64]
---

# Client Allocation Questions 

## Core Information
- Name: Suzhou Paipaitao Information Technology Co.,Ltd
- Website / Social Media: www.taopaipai.com
- DataCap Requested: 4.9TiB
- Addresses to be Notarized: f1g3jdihzsfldw3byfee627f7uyapg7gwwadorgsq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @NBAPLUS - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
