### ISSUE TITLE
Client Allocation Request for: 北京中电博顺智能设备技术有限公司

### ISSUE THREAD

**Issue by qingshui-wang** [keyko-io/filecoin-clients-onboarding#65]
---

# Client Allocation Questions 

## Core Information
- Name: 北京中电博顺智能设备技术有限公司
- Website / Social Media: www.bosonrobotics.com
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1uhubdateuntjmpje6yg4dwy6p5hjwxewuddueiy
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @qingshui-wang - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by qingshui-wang** [comment]
Hello,as your request, this is information:

1 Qingshui Wang, investor of Bosonrobotics (北京中电博顺智能设备技术有限公司)when i was working in Jinglong Capital, focusing in CleanTech Area several years ago;
   Found Partner, TokenDAO Capital，established Since 2017.9；investor of 1475, a famous Filecoin miner.

Social Media，Linkedin：https://www.linkedin.com/in/qingshui-wang-0b03671b/
2 Shawn Wang，over 13 years of PE/VC investment experience focused in TMT(Technology Media & Telecom). Data authentication, data authorization, data sharing and trading, became the common difficulties and pain points in many industries and fields such as precision marketing, data mining, AI and so on. Soon, Blockstack and Filecoin the two projects came into my eyes. Since 2016, I was prove to be an evangelists and investor of Web3.0 and IPFS.

I widely promotion and strongly recommend IPFS&Filecoin to many data terminal users, and Bosonrobotics was one of them, which was most interested about distributed storage and usage of their data collected globally .

3 Video and photo samples of thermal images of photovoltaic panels.

Bosonrobotics is a photovoltaic power station cleaning robot company, which has been operating for more than five years, covering 30-50 photovoltaic power stations around the world

The photovoltaic power station needs to clean the panel and analyze the working state of the equipment. While cleaning the dust, the robot will also collect the thermal imaging data of each board. The following is the demo data package link of JSON file package uploaded by a small power station every day

Link: https://pan.baidu.com/s/1QydCYMu6wRBWqNCR_ VpVfQ

Extraction code: 9sae

4 i would like to store the data 5-10 redundancy, storaged globally,but analysis in China.Reliable miner, have effective power above 5PB. And faster transmission is more preferred.




December 2, 2020 at 3:40 AM，Philipp Banhardt <notifications@github.com> 写道：



Hey @qingshui-wang - thanks for your request. Can you kindly add more information / context here on:

yourself , e.g. include links to social media / news mentions etc
your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
Thanks

**Comment by philippbanhardt** [comment]
Hey @qingshui-wang can you kindly add a little more context on the data you are looking to store (i.e. is it open / public, size of data set, who do you anticipate will be retrieving the data and with what frequency etc). Thanks

**Comment by qingshui-wang** [comment]
Waiting your reply

发自我的iPhone

**Comment by philippbanhardt** [comment]
Hey @qingshui-wang can you kindly add a little more context on the data you are looking to store (i.e. is it open / public, size of data set, who do you anticipate will be retrieving the data and with what frequency etc). Thanks

**Comment by qingshui-wang** [comment]
as your request, there is supplementary informaiton about our data:

https://drive.google.com/drive/folders/1vXA8me43_biaX4-2MasFHOnFXh8E7Q4R?usp=sharing







Hello,as your request, this is information:

1 Qingshui Wang, investor of Bosonrobotics (北京中电博顺智能设备技术有限公司)when i was working in Jinglong Capital, focusing in CleanTech Area several years ago;
   Found Partner, TokenDAO Capital，established Since 2017.9；investor of 1475, a famous Filecoin miner.

Social Media，Linkedin：https://www.linkedin.com/in/qingshui-wang-0b03671b/
2 Shawn Wang，over 13 years of PE/VC investment experience focused in TMT(Technology Media & Telecom). Data authentication, data authorization, data sharing and trading, became the common difficulties and pain points in many industries and fields such as precision marketing, data mining, AI and so on. Soon, Blockstack and Filecoin the two projects came into my eyes. Since 2016, I was prove to be an evangelists and investor of Web3.0 and IPFS.

I widely promotion and strongly recommend IPFS&Filecoin to many data terminal users, and Bosonrobotics was one of them, which was most interested about distributed storage and usage of their data collected globally .

3 Video and photo samples of thermal images of photovoltaic panels.

Bosonrobotics is a photovoltaic power station cleaning robot company, which has been operating for more than five years, covering 30-50 photovoltaic power stations around the world

The photovoltaic power station needs to clean the panel and analyze the working state of the equipment. While cleaning the dust, the robot will also collect the thermal imaging data of each board. The following is the demo data package link of JSON file package uploaded by a small power station every day

Link: https://pan.baidu.com/s/1QydCYMu6wRBWqNCR_ VpVfQ

Extraction code: 9sae

4 i would like to store the data 5-10 redundancy, storaged globally,but analysis in China.Reliable miner, have effective power above 5PB. And faster transmission is more preferred.


December 8, 2020 at 6:12 PM，Philipp Banhardt <notifications@github.com> 写道：






Hey @qingshui-wang can you kindly add a little more context on the data you are looking to store (i.e. is it open / public, size of data set, who do you anticipate will be retrieving the data and with what frequency etc). Thanks

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5gyf6o7i4i76lxttmrvnmgjasx7ba6p54xf4rzcrwfasggqyzrq 
#### Address 
> f1uhubdateuntjmpje6yg4dwy6p5hjwxewuddueiy
#### Datacap Allocated
> 5 TiB
