### ISSUE TITLE
Client Allocation Request for: CoinSummer

### ISSUE THREAD

**Issue by yuwenhui** [keyko-io/filecoin-clients-onboarding#66]
---

# Client Allocation Questions 

## Core Information
- Name: CoinSummer
- Website / Social Media: https://coinsummer.io
- DataCap Requested: 16TiB
- Addresses to be Notarized: f163yrswdzukl2oywmgcx3wgtkuljpqc3wlrsae6i
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @yuwenhui - thanks for your request, however at this time the foundation is only considering data cap requests <5TB. If you wish to make a new request for <5TB, then please do so through the app.
