### ISSUE TITLE
Client Allocation Request for: MOLeMART

### ISSUE THREAD

**Issue by hedoturkoglu** [keyko-io/filecoin-clients-onboarding#70]
---

# Client Allocation Questions 

## Core Information
- Name: MOLeMART
- Website / Social Media: www.molemart.com
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1ib7mmqlgrdzoeojt367toebpccynkdylt6tza6i
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @hedoturkoglu - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by hedoturkoglu** [comment]
•	About MOLeMART and myself

- Lei Lu https://www.linkedin.com/in/lulei/
20 years experience in Big Data and AI. 10 years as Senior Executives of fortune 1000 companies, 4 years as CEO of public company, 6 years as founder of Big Data Search Engine company of pharmaceutical industry.

- MOLeMART: http://www.molemart.com/
MOLeMART is a pharmaceutical intermediate B2B e-Commerce platform, which aims to connect buyers and suppliers. MOLeMART has world’s No.1 database of pharmaceutical industry, which introduces the most effective and efficient way for buyers to make purchases and for suppliers to demonstrate their products. 

•	History working on IPFS/Filecoin

MOLeMART was founded in 2014 with regional offices in China, Hongkong, Europe and North America. Our Big Data Search Engine search through entire drug discover process and store PiB level data in days. We’ve been looking for a cost efficient way to store data since day one we started our company. IPFS/Filecoin, as well as many other distributed storage innovation projects are the new technologies will eventually booming up our businesses like ours. We involved almost every corner of IPFS/Filecoin project, including: ICO in 2017; Angel investing filecoin ecosystem companies in 2018; Email exchange with Juan Benet in 2019; Community supporting in 2020; Data center and technical support in 13 countries across 5 continents in SR1; and etc. 

•	Type and source of the data looking to store on Filecoin

Data across 1,000+ sources pre-collected at MOLeMART.com, fake and incorrect information removed, doubtful information manipulated. Everything was indexed. E.g:
https://www.acs.org/: ACS – America Chemical Society
https://www.cas.org/products/scifinder: The most chemistry aware relevance engine in the industry
http://www.molbase.com/: Chemical e-commerce designed for small and medium-sized businesses
https://www.emolecules.com/: Business intelligence data and integrated ecommerce software for screening compound, chemical building blocks and primary antibody supply chains.

•	How you intend to store the data on Filecoin

As 47% of our customers are from NA, 26% of our customers are from EU, less than 2% of our customers are from OA, AF, and SA combined, we would prefer miners in NA/EU, and not likely miners in OA/AF/SA. China, Korean, Japan, and India are also the countries we would like to explore. We’ve been pushing miners to start little by little in these countries, and we could definitely help them again in data centers and field services.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2xnbs55molufj6aq3ntqvo5245sskepgg6k7zpd66xc6kbfqif6 
#### Address 
> f1ib7mmqlgrdzoeojt367toebpccynkdylt6tza6i
#### Datacap Allocated
> 5 TiB

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 5TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs

**Comment by hedoturkoglu** [comment]
Thanks for reaching out, Joao.

We were looking to store our data with Filecoin, but the experience is not
as good as centralized cloud services such as aliyun or aws. When we work
with Aliyun, everything goes so simple and we are able to get the storage
work done in several steps.

I don't understand a couple of things:
1st of all, why the filecoin team creates so many obstacles for people to
use. Most cloud service companies pay to get customers; why does the
filecoin team seem to be trying to push customers away.
Secondly, as far as I know, all cloud service companies hire sales and
marketing people looking to get customers to use more of their services. On
the contrary, the filecoin team hires a team of people looking to get
customers to use less. We store 5PB data with Aliyun and Qiniu Cloud; while
filecoin only allows us to store 5TB. It doesn't make much business sense
for us to store 99% of data with one company and 1% of data with another
company. Thinking about the cost and risk of managing 2 accounts from 2
companies, it's not worth it to save 1% of the storage cost.

BTW, we do use the other IPFS decentralized storage service, called Crust.
Very user friendly and we love it. We have over 1PB of data stored with
Crust, and we could get as many as 100 copies for free.

Regards,
Hedo
