### ISSUE TITLE
Client Allocation Request for: 灵动

### ISSUE THREAD

**Issue by wdw2913388515** [keyko-io/filecoin-clients-onboarding#72]
---

# Client Allocation Questions 

## Core Information
- Name: 西安灵动计算机系统有限公司
- Website / Social Media: https://www.lindensys.com/#/
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3v2zzsxfp527jfxmc5wn2kslpl6kqeyx5zmn3uquomwrxvjkv4g3hjo4rspifhgolio4l2c7crjofu6lmrhba
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @wdw2913388515 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
