### ISSUE TITLE
Client Allocation Request for: Tiannning

### ISSUE THREAD

**Issue by ROXtiGerf** [keyko-io/filecoin-clients-onboarding#73]
---

# Client Allocation Questions 

## Core Information
- Name: Tiannning
- Website / Social Media: https://github.com/CourteousBin/Neo-Beat
- DataCap Requested: 128GiB
- Addresses to be Notarized: f3vsaey2wmdzxqzmkzndgpztnxsvfgjumcvxvgwivubw5he5roqn2za7mpokvzsijroe5fhrjr2p7chnnhbdsq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @ROXtiGerf - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by ROXtiGerf** [comment]
I'm a slingshot participant, the project name is Neo Beat. demo: http://www.impool.com/NeoBeat .
I have attended the first phase of the slingshot and I want to continue.

**Comment by philippbanhardt** [comment]
Hey @ROXtiGerf can you kindly add a little more info about yourself (e.g. links to social profiles) and also to the type and source of data you are looking to store as a client. Thanks

**Comment by ROXtiGerf** [comment]
Sure, my slack handle is https://filecoinproject.slack.com/team/U01291X73JR. I‘m active in filecoin event like slingshot office hours and opening ceremony and so on. The data I store is from Curated Datasets for the Slingshot Competition. Free Music Archive & Internet Archive.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceai42emqom6sr3lhpfpjfswulbn7vfyfg3zlqytylbu4bpwmngzse 
#### Address 
> f3vsaey2wmdzxqzmkzndgpztnxsvfgjumcvxvgwivubw5he5roqn2za7mpokvzsijroe5fhrjr2p7chnnhbdsq
#### Datacap Allocated
> 137 GiB
