### ISSUE TITLE
Client Allocation Request for: The bigdata application case research center

### ISSUE THREAD

**Issue by 0xffee** [keyko-io/filecoin-clients-onboarding#74]
---

# Client Allocation Questions 

## Core Information
- Name: The bigdata application case research center
- Website / Social Media: https://www.huodongxing.com/org/380618161547
- DataCap Requested: 4TiB
- Addresses to be Notarized: f1yjo5zhrovw45zvmhu4ze7ve3dw6wvfouyirdggi
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @0xffee - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by 0xffee** [comment]
Hey @philippbanhardt ,

I am a blockchain specialist and IT industry entrepreneur. I hosted many activities for big data and blockchain to promate the bigdata and blockchain industry. You can find those activites on the https://www.huodongxing.com/org/380618161547. 
there are others news link http://www.yidianzixun.com/article/0JH3qrOG and https://www.qklct.com/blockchain/14853/.

I created the technology stack of blockchain 4.0 , this stack consist of blockchain smart contract + ipfs + docker cloud computing.
you can find the description on https://github.com/0xffee/blockchain40. And I developed the demo of ethereum + ipfs for neighbourhood security to take part in the Beijing hackathon in 2019 .  the demo link is https://github.com/0xffee/ChaoyangDama .

Now I am developing the solution for video and VR with blockchain , so I hope to store the video and VR media type file to filecoin. those source material will be private , when those source material are beautified , they will be published and are public data.

I hope to store my data to filecoin for low cost , redundancy and location.

**Comment by philippbanhardt** [comment]
Hey @0xffee at this time the foundation is only considering data cap requests for open / public and web3 data - so I will not be able to grant this request. Other notaries (when available) may have different policies as to the type / source of data, and the foundation's policies may change too in the future - so I recommend you follow progress on the Filecoin Plus initiative via the Slack channel. In any case thanks for you application!
