### ISSUE TITLE
Client Allocation Request for: CoinSummer

### ISSUE THREAD

**Issue by yuwenhui** [keyko-io/filecoin-clients-onboarding#81]
# Client Allocation Questions 

## Core Information
- Name: CoinSummer
- Website / Social Media: https://coinsummer.io
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3s47wuxlqofvu6cnhucyiwa4zmw4cmg43g263mdbam32fvmrdq6aq6bt27jrmownkkckyz4p4ljiy2lrpgcbq
- Notary Requested: philippbanhardt

-----------------------------

**Comment by philippbanhardt** [comment]
Hey @yuwenhui - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- **type, size and source** of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by yuwenhui** [comment]
Hey @philippbanhardt - here are our information:

**Question1:**
Wenhui Yu, co-funder of CoinSummer Lab. I have been a Web Developer and Product Manager for about 6 years, and worked on image recognition use deep leaning tow years ago. I am focus on Filecoin and Polkadot develop and research currently.

Social Media: [Linkedin](https://www.linkedin.com/in/yuwenhui)

**Question2:**
I and our team created and maintaining Filecoin Chinese technology WeChat group with more than 1k miners and developers. There are tens of thoursands of messages every day including hardware configuration, mining tutorial, troubleshooting, development sharing, bug trace and so on. We believe that these are the most active and useful technical community for Filecoin ecosystem.

I also provide proof parameters(v25, v26, v27) and Filecoin blockchain synchronization datastore backup mirrors on Mainland China from the Filecoin TestNet. More than 200 miners use our download service for free.

- [CoinSummer Filecoin proofs parameters mirrors](https://filecoin.coinsummer.io/)
- [Blockchain synchronization datastore backup](https://filecoin.coinsummer.io/datastore.html)

Additionally, we organized and collected [awesome Filecoin resources repo](https://github.com/CoinSummer/filecoin) for Chinese commuity. Including common resource links, lotus node operations, common storage miner operations, seal worker operations, deal operations, environment variables, debugging, benchmarks, frequently asked questions, etc.

**Question3:**
Public data such as:
[Openimages](https://storage.googleapis.com/openimages/web/index.html): a dataset of ~9 million URLs to images that have been annotated with image-level labels and bounding boxes spanning thousands of classes.
[ImageNet](http://www.image-net.org/): an image database organized according to the WordNet hierarchy.

There will be more than 10TiB of all these dataset with `.tar` format.

**Question4:**
Firstly, we store these dataset on Filecoin for redundancy, additionally, we are planning to build a decentralized image dataset which everyone can use to train their own Machine-learning and AI models. We are developing more feature to using Filecoin and IPFS as the storage solution.

**Comment by philippbanhardt** [comment]
Hey @yuwenhui thanks for providing the additional information. Are you OK to post here transaction links to the storage deals, once awarded data cap? Also on a related note - wanted to highlight that we are keen to foster decentralization of the network, so would encourage clients to store (redundantly) across a number of miners, as well as refrain from self-dealing as much as possible.

**Comment by philippbanhardt** [comment]
@yuwenhui quick nudge on the above

**Comment by yuwenhui** [comment]
@philippbanhardt  Yes, i will store my data file to a number of miners for decentralization and post all the transaction links of those deals to here after i granted the data cap.
