### ISSUE TITLE
Client Allocation Request for: Filbox

### ISSUE THREAD

**Issue by kimchibazinga** [keyko-io/filecoin-clients-onboarding#82]
---

# Client Allocation Questions 

## Core Information
- Name: Filbox
- Website / Social Media: https://filbox.keystore.com/databrowser/ 
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3umho76jhnreafz5nraeyob25kidea26xz5xzewpe5glc45ullz55bzusfnfrk2nlb3ibd3aiphhmblqpuvda
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @kimchibazinga - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- **type, size and source** of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by kimchibazinga** [comment]
Sure, glad to provide the info here.

> yourself , e.g. include links to social media / news mentions etc

I’m Kimmy Wen, Brand Manager of Keystore Group (Filecoin associated brand - KeyPool and Filbox) and the go-to market person for Filbox. Equipped with profound tech experience in Intel, Marvell, Phillips, TechCrunch, 360yunpan, we are a team committed to continuously envolve and improve the Filecoin ecosystem

Company Linkedin Page: https://www.linkedin.com/company/keystoregroup 
Company WeChat Page: Keystore Group Official Account: keystore服务中心, KeyPool Official Account: KeyPool；
Recent Mentions: https://news.sina.com.cn/o/2020-08-21/doc-iivhuipn9894212.shtml; https://www.8btc.com/media/661286；https://www.lieyuncj.com/p/16555；https://www.8btc.com/article/639645；https://www.chainnews.com/articles/929997034784.htm?from=timeline&isappinstalled=0；https://mp.weixin.qq.com/s/9H2H8NJ5X73Y7g_At2Szig 

Team members:
Kimmy Wen: https://www.linkedin.com/in/kimmy-sijiewen/ 
Savage LI: https://www.linkedin.com/in/savage-li-077a48101/ 
Felix Zhou: https://www.linkedin.com/in/felix-zhou-2b40b92a/ 
Fay: https://blog.csdn.net/fay462298322 

> your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc

Slingshot phase1：
- Storage Awards: 275 Fil
- Persona User Awards (First Place)：1500 Fil
- Booster Awards：50 FIl

IFIC Shanghai: 
- First Prize in Innovation International Fintech Innovation Conference Competition (IFIC Shanghai) (October 2020)

We’ve also applied for Devgrants Programme and Filecoin Accelerator Programme and are actively participating in Slingshot and Filecoin community (Slack, WeChat group etc.,).

> type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc

We’ve been continuously storing curated datasets into the Filecoin network which are open for other users to access. Currently we are using curated datasets from Starry Sky in Yunnan (http://hlmxy.file123.pro:9006/), Filecoin Proofs (https://proofs.filecoin.io/), NYC Trip Record Data (https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page) and Linux ISO (https://www.linuxlookup.com/linux_iso) and we are planning to continue storing public datasets into Filecoin. 

> how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

We maintains a daily miner list that selects active and reputable miners from Lotus query-ask and other storage market application (such as https://storage.codefi.network/). Redundancy: ~10 copies; Location: Asia, EU, US

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccjx3yjyy34hgs63wdnoq2k2oyg4k5yocnfqflx3ztgovdghl5ke 
#### Address 
> f3umho76jhnreafz5nraeyob25kidea26xz5xzewpe5glc45ullz55bzusfnfrk2nlb3ibd3aiphhmblqpuvda
#### Datacap Allocated
> 5 TiB
