### ISSUE TITLE
Client Allocation Request for: XJYT

### ISSUE THREAD

**Issue by jiayi-boot** [keyko-io/filecoin-clients-onboarding#85]
---

# Client Allocation Questions 

## Core Information
- Name: XJYT
- Website / Social Media: 
- DataCap Requested: 8TiB
- Addresses to be Notarized: f010035
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @jiayi-boot thanks for your request, however at this time the foundation is only considering requests <5TB.
