### ISSUE TITLE
Client Allocation Request for: chengmu

### ISSUE THREAD

**Issue by jiayi-boot** [keyko-io/filecoin-clients-onboarding#86]
---

# Client Allocation Questions 

## Core Information
- Name: chengmu
- Website / Social Media: 
- DataCap Requested: 5TiB
- Addresses to be Notarized: f021255
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @jiayi-boot - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- **type, size and source** of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Also I noticed that you are applying with a miner ID; this verification program is for clients looking to store data on the Filecoin network. While clients can also be miners, we do not encourage self serving and expect that clients store useful data across a wide range of miners to foster decentralization. Bear in mind that this is the opinion of the Filecoin Foundation as the first notary. Other notaries may adopt different policies.

Thanks
