### ISSUE TITLE
Client Allocation Request for: [IPFS Found]

### ISSUE THREAD

**Issue by IPFSUnion** [keyko-io/filecoin-clients-onboarding#87]
# Client Allocation Questions 

## Core Information
- Name: IPFS Found （IPFSUNION）  
- Website / Social Media: https://filecoin.in/        （https://ipfsunion.cn）
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3rf334djo4e76f44hz6tbkh5maerg42nr5b5squsb7kty336zv6pdnnwhyc2qaijpq2dwkpyy3fwfeofjtpja

### **1. yourself , e.g. include links to social media / news mentions etc**

 **IPFS Found**  is developed by the IPFSUNION team, Based on Filecoin network, IPFS Found is designed as a storage and retrieval to help users store various types of files, including text, picture, audio, video, etc. And it supports storage of multiple data sizes. We aim to build more decentralized, stable and robust data storage platform.

 - About IPFSUNION:
 - Official website：https://ipfsunion.cn/
 - Self-developed Filecoin browser：https://filscout.io
 - Twitter: https://twitter.com/ipfsunion_cn
 - Github：https://github.com/IPFSUnion 
 - Zhihu：https://zhuanlan.zhihu.com/p/173753718

### **2. your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc**

- Participated in Filecoin Security Research Fellowship, https://security.filecoin.io/, and submitted six critical bug reports to the security@filecoin.io, you can contact the @why to prove it.

- Participated in Filecoin Devgrants Program and submitted three PR(app-dev, docs and Storage Web Application)
https://github.com/filecoin-project/devgrants/pull/76
https://github.com/filecoin-project/devgrants/pull/74
https://github.com/filecoin-project/devgrants/pull/113

- Participated in Space Race 1 and  reached the NO.7, and join the private meeting call with Juan Benet. 
https://spacerace.filecoin.io/

- Participated in SR2 Slingshot competition, and the “IPFS Found”project (https://filecoin.in/) won the Community Call-out Awards
https://filecoin.io/blog/slingshot-phase-1-recap/

- Developed the Filecoin explore “Filscout”(https://filscout.io ) which has supported 5 languages and is widely used in the Filecoin communities .

- Be nominated as the member of Filecoin Foundation’s miner group by Juan Benet. @philippbanhardt 

-  Participated in the Filecoin liftoff week to present the Dev/Explorers and Miner Slot
https://www.figma.com/file/nTDG1PXJYwrRm1p1rpaVZB/Filecoin-Liftoff-Week?node-id=0%3A1 

### 3. type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc

IPFS Found is always storing the real data from [curated data](https://github.com/filecoin-project/slingshot/blob/master/datasets.md) to the Filecoin network during the slingshot phase1, we have stored the following data:
https://proofs.filecoin.io/
https://trusted-setup.filecoin.io/
https://ghtorrent.org/
https://storage.googleapis.com/openimages/web/index.html
https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge
https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia   
https://www.kaggle.com/borismarjanovic/price-volume-data-for-all-us-stocks-etfs
http://hlmxy.file123.pro:9006

for now  we are storing the MySQL database dumps 
https://ghtorrent.org/downloads.html

In the future, IPFS Found will store more and more real data to the Filecoin network

### 4. how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
IPFS Found will choose some large and stable miners to store the real data; 
Each data will be stored in at least four different miners, and each data will be stored in 10 copies；
The source data will be stored in my local service.

Besides, we have 5 stable official miners f023530, f01231, f016398, f021479, f070932 with total 60.37 PiB power until now.

**Comment by philippbanhardt** [comment]
Hey @IPFSUnion thanks for providing the additional information. Are you OK to post here transaction links to the storage deals, once awarded data cap? Also on a related note - wanted to highlight that we are keen to foster decentralization of the network, so would encourage clients to store (redundantly) across a number of miners, as well as not engage in excessive / unfair self-dealing.

**Comment by IPFSUnion** [comment]
@philippbanhardt Yes, I will post the the data-deal info like the slingshot requirements once awarded dataCap. 

- **IPFS Found** will continue to storage the data from curated dataset of slingshot list. 

- And  the dataCap will be assigned to different miners, less than 20 percents will be stored in my own miner, one file will be stored in 10 copies for different miners.

- Every posted transaction info will include information as follows:

`deal_id   miner_id    dataCID    address    deal_status    file_name    file_format    file_size    date     `

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebralxbyhkfgwhrvnzf7yyvrm4yaiiufu67cxay6pcnvb2zmkzj7i 
#### Address 
> f3rf334djo4e76f44hz6tbkh5maerg42nr5b5squsb7kty336zv6pdnnwhyc2qaijpq2dwkpyy3fwfeofjtpja
#### Datacap Allocated
> 5 TiB

**Comment by IPFSUnion** [comment]
thanks @philippbanhardt
