### ISSUE TITLE
Client Allocation Request for: ZhiLanBoFeng

### ISSUE THREAD

**Issue by KingKongOne** [keyko-io/filecoin-clients-onboarding#88]
---

# Client Allocation Questions 

## Core Information
- Name: ZhiLanBoFeng
- Website / Social Media: zhilanbofeng.cn/@KingKong @JXin song on the Filecoin Slack
- DataCap Requested: 1PiB
- Addresses to be Notarized: f1rlv5cnub6j5ndpvk25zxs4jfqwch5a6uhy3s3ia
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @KingKongOne thanks for your request, however at this time the foundation is only considering requests <5 TB.
