### ISSUE TITLE
Client Allocation Request for: liyiping

### ISSUE THREAD

**Issue by lyp830414** [keyko-io/filecoin-clients-onboarding#89]
---

# Client Allocation Questions 

## Core Information
- Name: liyiping
- Website / Social Media: https://blog.csdn.net/weixin_47733790/
- DataCap Requested: 4TiB
- Addresses to be Notarized: f1jy3blozja7edk7firimlylpxpqkqzrx34grkcgy
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @lyp830414 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- **type, size and source** of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by lyp830414** [comment]
About myself: 
    CSDN:   https://blog.csdn.net/weixin_47733790
    News： https://www.lianshijie.com/bottosnotice/82709
    Github:  https://github.com/lyp830414
    Twitter:   https://twitter.com/CBuilty 

I am blockchain developer and the specialist of technology for file system and data storage system. I am developing the application for blockchain and need to data mining for record of blockchain of EOS  and Hyperledger fabric blockchain.

In 2019 I took part in the Wanxiang Hackthon with IPFS : My project page is https://github.com/Wanxiang-Blockchain-Hackathon-2020/N07-Yiqingbielian 

All of data for my project are public and from the blockchain transaction ,for example, Filecoin ,EOS and hyperledger fabric blockchain, every week I need near 1TB disk space to save my web3 blockchain data.

And I like  more low price data storage solution like filecoin for redundancy.

Thanks!

**Comment by philippbanhardt** [comment]
Hey @lyp830414 thanks for providing the additional information. Are you OK to post here transaction links to the storage deals, once awarded data cap? Also on a related note - wanted to highlight that we are keen to foster decentralization of the network, so would encourage clients to store (redundantly) across a number of miners, as well as refrain from self-dealing as much as possible.

**Comment by lyp830414** [comment]
Yes, when I am granted the data cap , I will store my data file to a number of miners for decentralization and  post my transaction links of those deals to here.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebda6i4zjbinu4mnsa2a334ewvsmadilar6ktrhzw7nuon5mpxejy 
#### Address 
> f1jy3blozja7edk7firimlylpxpqkqzrx34grkcgy
#### Datacap Allocated
> 4 TiB
