### ISSUE TITLE
Client Allocation Request for: Lin JW

### ISSUE THREAD

**Issue by linjw1008** [keyko-io/filecoin-clients-onboarding#92]
---

# Client Allocation Questions 

## Core Information
- Name: Lin JW
- Website / Social Media: https://blog.csdn.net/linjw1008
- DataCap Requested: 4TiB
- Addresses to be Notarized: f1fpa54bz6hfang5j3nlmk6ieqcv4kda2zcqv3r5i
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @linjw1008 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- **type, size and source** of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
