### ISSUE TITLE
Client Allocation Request for: ZhiLanBoFeng

### ISSUE THREAD

**Issue by KingKongOne** [keyko-io/filecoin-clients-onboarding#95]
---

# Client Allocation Questions 

## Core Information
- Name: ZhiLanBoFeng
- Website / Social Media: zhilanbofeng.cn/@KingKong @jxin song on the Filecoin Slack
- DataCap Requested: 2TiB
- Addresses to be Notarized: f1rlv5cnub6j5ndpvk25zxs4jfqwch5a6uhy3s3ia
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @KingKongOne  - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by KingKongOne** [comment]
website:https://www.zhilanbofeng.cn/

**Comment by KingKongOne** [comment]
website:https://www.zhilanbofeng.cn/
news mentions:

**Comment by KingKongOne** [comment]
#### 1 yourself , e.g. include links to social media / news mentions etc

Website:https://www.zhilanbofeng.cn/

Social Media:  [@KingKong](https://github.com/KingKong) on the Filecoin Slack

News mentions:

https://www.sohu.com/a/409418012_99893063?_f=index_pagefocus_7]

https://www.jinse.com/news/blockchain/788470.html

https://www.jinse.com/member?id=253584

https://baike.baidu.com/item/%E6%99%BA%E5%B2%9A%E5%8D%9A%E4%B8%B0%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/51524053?fr=aladdin



#### 2 your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc

Since 2018,I have been followed the filecoin project, the main activities are as follows:

1. In the early stage, assembled a technical team for related development;
2. Before the mainnet launch, participated in all testing phases;
3. In-depth study of lotus code,and suggestions on performance optimization;
4. Actively promote filecoin and ipfs technologies, and set up a thousand-scale cluster in the IDC for technical development and trial;
5. Participated in official activities, such as spacerace1, spacerace2, slingshot2, etc.

#### 3 type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc

The stored data is public data, mainly AI-related data, including natural language recognition, image recognition, face recognition etc.
source and size:

NEAR-VI-Dataset：175GB
Google Open Images: 456GB
Tencent Corpus for Chinese Words and Phrases: 6.3GB
COVID-19 Open Research Dataset: 19GB
tao dataset:225G
an image database organized according to the WordNet hierarchy: 1.2TB



#### 4 how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Currently, data needs to be stored on the ipfs network for verification of storage technology.To ensure data security, more than three copies of each data need to be stored
Data is mainly stored in Asian miners;
The selection of miners is mainly based on the top miners, and do some screening, and store as follows:

1. top and trusted miner:  60%;
2. trusted miners:  20%;
3. Other high-quality miners: 10% ;
4. Self-storage: 10%  for technical verification;

**Comment by philippbanhardt** [comment]
hey @KingKongOne with the data listed above I don't really see the need for 5 TiB of data cap right now, esp I lack context on the image database. Can you elaborate a little more and kindly rethink requested data cap? Also - if you were awarded datacap, would you be OK in posting deal transactions here? Thanks

**Comment by KingKongOne** [comment]
hey  @philippbanhardt 

1. Can you elaborate a little more and kindly rethink requested data cap?

So far, the data I consider to store is only 2TiB. I have modified the data cap to 2TiB. If I need to upload more data in the future, can the data cap be modified?

2. Would you be OK in posting deal transactions here? 

Of course, I will post the transaction here

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedacuyyw2vkw66jpv3ahslwodoe6diaescamublk5iriivvv5426a 
#### Address 
> f1rlv5cnub6j5ndpvk25zxs4jfqwch5a6uhy3s3ia
#### Datacap Allocated
> 2 TiB
