### ISSUE TITLE
Client Allocation Request for: Chao Gao

### ISSUE THREAD

**Issue by chasingegg** [keyko-io/filecoin-clients-onboarding#96]
---

# Client Allocation Questions 

## Core Information
- Name: Chao Gao
- Website / Social Media: https://chasingegg.github.io
- DataCap Requested: 4TiB
- Addresses to be Notarized: f1q7y3althzqmhr43mdvytikhtwd6srfqb3ewizji
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @chasingegg - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
