### ISSUE TITLE
Client Allocation Request for: Voodfy Inc

### ISSUE THREAD

**Issue by Leeaandrob** [keyko-io/filecoin-clients-onboarding#97]
---

# Client Allocation Questions 

## Core Information
- Name: Voodfy Inc
- Website / Social Media: https://beta.voodfy.com
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3wfovmet4goxalkks7mobcgeraxy5ln5qfwchx2aqvlb2hsykjsxiufkyjuznlertgjnl4ezmdq2chj3w67ia
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @Leeaandrob - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by philippbanhardt** [comment]
Adding here that https://github.com/mgoelzer can vouch for the team after working with them throughout the Tachyon accelerator program. @Leeaandrob would still be great if you can share here publicly answers to the above questions. Thanks!

**Comment by philippbanhardt** [comment]
@Leeaandrob quick nudge on the above, thanks

**Comment by Leeaandrob** [comment]
Voodfy is professional video hosting for everyone.
@voodfy / @leeaandrob Twitter
https://blog.textile.io/video-on-filecoin-using-voodfy-project-and-powergate/
https://filecoin.io/blog/mainnet-liftoff-video-storage/

Four years ago I am working a startup called Paratii where We were building a decentralized video player using IPFS, my first contact with Filecoin happened this year when Eric Tang(Livepeer) present to me all ecosystem and community around Filecoin. with the possibility to store in a decentralized way I realize that I could build a decentralized video platform. I accept the challenge and build the Voodfy using IPFS+Filecoin(Powergate) and the transcoder using Livepeer during the process I received two grants to build an MVP and currently this MVP is possible to access using https://beta.voodfy.com.

All videos are store using IPFS as the hot layer strategy and Filecoin as our cold layer strategy for private and public assets, videos, etc.
Our strategy is to store using redundancy and the best location near for the user that is storing using Voodfy.

@philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @Leeaandrob thanks, can you kindly add more information / links to yourself (e.g. your LinkedIn profile) and also link to the grants you have received? 

Also: (1) can you elaborate more on the where the video data will be coming from / frequency of retrieval, and (2) would you be OK in posting here links to the deal transactions?

Thanks

**Comment by philippbanhardt** [comment]
Hey @Leeaandrob quick nudge on the above given we chatted last week during the Tachyon mentoring session.

**Comment by Leeaandrob** [comment]
@philippbanhardt is it possible open the issue again with the launch the new portal 100 % IPFS hosted the Voodfy?

**Comment by Leeaandrob** [comment]
Answering the last questions.


My LinkedIn: http://linkedin.com/in/leandro-b-a0b98259

Yes it not a problem for me make the public all deal made by the Voodfy storing content with the users

The content will be uploaded and generated by the Portal and Store at our IPFS nodes and Filecoin using the integration with Textile Powergate.

**Comment by Leeaandrob** [comment]
@philippbanhardt any news?
