### ISSUE TITLE
Client Allocation Request for: Xuenan Xu

### ISSUE THREAD

**Issue by wsntxxn** [keyko-io/filecoin-clients-onboarding#99]
---

# Client Allocation Questions 

## Core Information
- Name: Xuenan Xu
- Website / Social Media: https://wsntxxn.github.io
- DataCap Requested: 4TiB
- Addresses to be Notarized: f1kc7aibdvmviwpp2imco5w6pxbzbhttdttxt6j2q
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @wsntxxn - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
